"""Layer-3 one-dimensional minidisk and limit-cycle tools."""

from .audit_metrics import (
    EnergyResidualMetrics,
    energy_residual_metrics,
    energy_residual_metrics_from_profile,
    mdot_continuity_residual,
    normalized_mdot_continuity_residual,
    pointwise_energy_residual,
)
from .diffusion_solver import (
    DiffusionStepResult,
    explicit_diffusion_step,
    mass_from_surface_density,
    prescribed_scurve_step,
    update_branch_state,
    viscous_diffusion_rhs,
)
from .entropy_advection import (
    centered_gradient,
    entropy_gradient_consistency_error,
    entropy_gradient_log_formula,
    entropy_temperature_gradient,
    mdot_from_vr,
    q_advective,
    radial_gradient,
    slope_limited_gradient,
    specific_internal_energy,
    total_pressure,
    xi_eff,
)
from .grid import RadialGrid, make_log_grid
from .global_slim import (
    GlobalSlimParams,
    GlobalSlimProfile,
    GlobalSlimRelaxationResult,
    alpha_viscosity,
    evaluate_global_slim_profile,
    integrated_energy_residual,
    keplerian_omega,
    keplerian_specific_angular_momentum,
    keplerian_stress,
    keplerian_viscous_heating,
    radial_velocity_from_angular_momentum,
    relax_temperature_energy_balance,
    vertical_structure_arrays,
)
from .isolated_slim_solver import (
    IsolatedSlimContinuationResult,
    IsolatedSlimParams,
    IsolatedSlimProfile,
    IsolatedSlimSolveResult,
    best_local_temperature_profile,
    choose_sigma_root,
    continue_isolated_slim_branch,
    evaluate_isolated_slim_profile,
    isolated_residual_vector,
    profile_from_state_vector,
    required_keplerian_stress,
    sigma_roots_for_temperature,
    solve_isolated_slim_disk,
    solve_sigma_profile_from_temperature,
    state_vector_from_profile,
)
from .limit_cycle import OneZoneCycleResult, one_zone_cycle
from .source_profiles import gaussian_source, gaussian_source_on_grid, normalize_surface_source
from .transonic_collocation import (
    TransonicSlimParams,
    TransonicSlimProfile,
    TransonicSolveResult,
    collocation_residual,
    computational_grid,
    initial_guess_from_reduced_solver,
    initial_guess_from_repaired_reduced_solver,
    jac_sparsity_pattern,
    pack_state,
    profile_from_state_vector as transonic_profile_from_state_vector,
    replace_mdot as replace_transonic_mdot,
    solve_transonic_outer_branch,
    state_bounds,
    unpack_state,
)
from .transonic_continuation import TransonicContinuationResult, continue_in_mdot, remap_profile_to_new_sonic_grid
from .transonic_local import (
    AlgebraicTransonicState,
    LocalPartials,
    SonicDiagnostics,
    algebraic_state,
    analytic_state_partials,
    differential_matrix,
    differential_residual,
    entropy_gradient_log,
    finite_difference_state_partials,
    local_gradient,
    sonic_diagnostics,
    state_partials,
    xi_eff_from_gradient,
)
from .transonic_potential import PaczynskiWiitaPotential
from .transonic_thermo import (
    TransonicVerticalState,
    integrated_stress,
    radiative_cooling,
    surface_density,
    vertical_state,
)
from .winds import energy_limited_wind, q_available, q_edd_vertical, wind_energy_per_mass

__all__ = [
    "AlgebraicTransonicState",
    "DiffusionStepResult",
    "EnergyResidualMetrics",
    "GlobalSlimParams",
    "GlobalSlimProfile",
    "GlobalSlimRelaxationResult",
    "IsolatedSlimContinuationResult",
    "IsolatedSlimParams",
    "IsolatedSlimProfile",
    "IsolatedSlimSolveResult",
    "LocalPartials",
    "OneZoneCycleResult",
    "PaczynskiWiitaPotential",
    "RadialGrid",
    "SonicDiagnostics",
    "TransonicSlimParams",
    "TransonicSlimProfile",
    "TransonicSolveResult",
    "TransonicContinuationResult",
    "TransonicVerticalState",
    "algebraic_state",
    "analytic_state_partials",
    "alpha_viscosity",
    "best_local_temperature_profile",
    "centered_gradient",
    "choose_sigma_root",
    "collocation_residual",
    "computational_grid",
    "continue_in_mdot",
    "continue_isolated_slim_branch",
    "differential_matrix",
    "differential_residual",
    "energy_residual_metrics",
    "energy_residual_metrics_from_profile",
    "entropy_gradient_log",
    "finite_difference_state_partials",
    "explicit_diffusion_step",
    "gaussian_source",
    "gaussian_source_on_grid",
    "entropy_gradient_consistency_error",
    "entropy_gradient_log_formula",
    "entropy_temperature_gradient",
    "energy_limited_wind",
    "evaluate_global_slim_profile",
    "evaluate_isolated_slim_profile",
    "integrated_energy_residual",
    "integrated_stress",
    "initial_guess_from_reduced_solver",
    "initial_guess_from_repaired_reduced_solver",
    "isolated_residual_vector",
    "jac_sparsity_pattern",
    "keplerian_omega",
    "keplerian_specific_angular_momentum",
    "keplerian_stress",
    "keplerian_viscous_heating",
    "local_gradient",
    "make_log_grid",
    "mass_from_surface_density",
    "mdot_continuity_residual",
    "mdot_from_vr",
    "normalized_mdot_continuity_residual",
    "normalize_surface_source",
    "one_zone_cycle",
    "pointwise_energy_residual",
    "pack_state",
    "profile_from_state_vector",
    "prescribed_scurve_step",
    "q_advective",
    "q_available",
    "q_edd_vertical",
    "radial_gradient",
    "radial_velocity_from_angular_momentum",
    "radiative_cooling",
    "relax_temperature_energy_balance",
    "replace_transonic_mdot",
    "remap_profile_to_new_sonic_grid",
    "required_keplerian_stress",
    "sigma_roots_for_temperature",
    "sonic_diagnostics",
    "slope_limited_gradient",
    "solve_isolated_slim_disk",
    "solve_sigma_profile_from_temperature",
    "solve_transonic_outer_branch",
    "state_partials",
    "state_bounds",
    "state_vector_from_profile",
    "specific_internal_energy",
    "surface_density",
    "total_pressure",
    "transonic_profile_from_state_vector",
    "unpack_state",
    "update_branch_state",
    "vertical_state",
    "viscous_diffusion_rhs",
    "vertical_structure_arrays",
    "wind_energy_per_mass",
    "xi_eff_from_gradient",
    "xi_eff",
]
