"""Layer-3 one-dimensional minidisk and limit-cycle tools."""

from .audit_metrics import (
    EnergyResidualMetrics,
    energy_residual_metrics,
    energy_residual_metrics_from_profile,
    mdot_continuity_residual,
    normalized_mdot_continuity_residual,
    pointwise_energy_residual,
)
from .diffusion_solver import (
    DiffusionStepResult,
    explicit_diffusion_step,
    mass_from_surface_density,
    prescribed_scurve_step,
    update_branch_state,
    viscous_diffusion_rhs,
)
from .entropy_advection import (
    centered_gradient,
    entropy_gradient_consistency_error,
    entropy_gradient_log_formula,
    entropy_temperature_gradient,
    mdot_from_vr,
    q_advective,
    radial_gradient,
    slope_limited_gradient,
    specific_internal_energy,
    total_pressure,
    xi_eff,
)
from .grid import RadialGrid, make_log_grid
from .global_slim import (
    GlobalSlimParams,
    GlobalSlimProfile,
    GlobalSlimRelaxationResult,
    alpha_viscosity,
    evaluate_global_slim_profile,
    integrated_energy_residual,
    keplerian_omega,
    keplerian_specific_angular_momentum,
    keplerian_stress,
    keplerian_viscous_heating,
    radial_velocity_from_angular_momentum,
    relax_temperature_energy_balance,
    vertical_structure_arrays,
)
from .isolated_slim_solver import (
    IsolatedSlimContinuationResult,
    IsolatedSlimParams,
    IsolatedSlimProfile,
    IsolatedSlimSolveResult,
    best_local_temperature_profile,
    choose_sigma_root,
    continue_isolated_slim_branch,
    evaluate_isolated_slim_profile,
    isolated_residual_vector,
    profile_from_state_vector,
    required_keplerian_stress,
    sigma_roots_for_temperature,
    solve_isolated_slim_disk,
    solve_sigma_profile_from_temperature,
    state_vector_from_profile,
)
from .limit_cycle import OneZoneCycleResult, one_zone_cycle
from .source_profiles import gaussian_source, gaussian_source_on_grid, normalize_surface_source
from .winds import energy_limited_wind, q_available, q_edd_vertical, wind_energy_per_mass

__all__ = [
    "DiffusionStepResult",
    "EnergyResidualMetrics",
    "GlobalSlimParams",
    "GlobalSlimProfile",
    "GlobalSlimRelaxationResult",
    "IsolatedSlimContinuationResult",
    "IsolatedSlimParams",
    "IsolatedSlimProfile",
    "IsolatedSlimSolveResult",
    "OneZoneCycleResult",
    "RadialGrid",
    "alpha_viscosity",
    "best_local_temperature_profile",
    "centered_gradient",
    "choose_sigma_root",
    "continue_isolated_slim_branch",
    "energy_residual_metrics",
    "energy_residual_metrics_from_profile",
    "explicit_diffusion_step",
    "gaussian_source",
    "gaussian_source_on_grid",
    "entropy_gradient_consistency_error",
    "entropy_gradient_log_formula",
    "entropy_temperature_gradient",
    "energy_limited_wind",
    "evaluate_global_slim_profile",
    "evaluate_isolated_slim_profile",
    "integrated_energy_residual",
    "isolated_residual_vector",
    "keplerian_omega",
    "keplerian_specific_angular_momentum",
    "keplerian_stress",
    "keplerian_viscous_heating",
    "make_log_grid",
    "mass_from_surface_density",
    "mdot_continuity_residual",
    "mdot_from_vr",
    "normalized_mdot_continuity_residual",
    "normalize_surface_source",
    "one_zone_cycle",
    "pointwise_energy_residual",
    "profile_from_state_vector",
    "prescribed_scurve_step",
    "q_advective",
    "q_available",
    "q_edd_vertical",
    "radial_gradient",
    "radial_velocity_from_angular_momentum",
    "relax_temperature_energy_balance",
    "required_keplerian_stress",
    "sigma_roots_for_temperature",
    "slope_limited_gradient",
    "solve_isolated_slim_disk",
    "solve_sigma_profile_from_temperature",
    "state_vector_from_profile",
    "specific_internal_energy",
    "total_pressure",
    "update_branch_state",
    "viscous_diffusion_rhs",
    "vertical_structure_arrays",
    "wind_energy_per_mass",
    "xi_eff",
]
