"""Direct regular-domain refinement from the best sonic-buffer root."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot

from run_transonic_outer_slope_calibration_audit import fmt
from run_transonic_two_domain_mesh_validation import combined_profile_arrays, load_checkpoint, make_params
from run_transonic_two_domain_sonic_refinement_sprint import (
    CHECKPOINT_DIR as SPRINT_CHECKPOINT_DIR,
    MAX_NFEV_BUFFER_POLISH,
    MAX_NFEV_BUFFER_RELEASE,
    SOURCE_CHECKPOINT,
    attach_stage,
    buffer_audit,
    buffer_row_with_reference,
    buffer_to_buffer_seed,
    make_buffer_params,
    save_checkpoint,
    solve_buffer,
    source_first_slope,
)


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_two_domain_direct_regular_refinement.md"
BEST_BUFFER_CHECKPOINT = SPRINT_CHECKPOINT_DIR / "delta0p02_Nreg64_defect_preserving_0p90277664.npz"
DIRECT_TARGETS = (128,)
STAGED_TARGETS = (96, 128)
GATE_LIMIT = 5.0e-5


def load_row(path: Path) -> tuple[np.ndarray, dict[str, object]]:
    with np.load(path, allow_pickle=False) as data:
        return np.asarray(data["x"], dtype=float), json.loads(str(data["row_json"].item()))


def write_table(rows: list[dict[str, object]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Two-Domain Direct Regular Refinement",
        "",
        "Generated by `scripts/run_transonic_two_domain_direct_regular_refinement.py`.",
        "",
        "Starts from the best sonic-buffer checkpoint (`Delta_s=0.02`, `N_regular=64`) and tests whether high regular-domain resolution fails because of the prior coarsening path or because the refinement itself is still unstable.",
        "",
        "| path | label | stage | N regular | N inner | physical | dominant | patch | regular R | regular E | outer R | far omega | D | C1 | C2 | K | Rson/rg | dRson | lambda0 | dlambda | int adv | dint adv | local splits | local max | nfev | success | message |",
        "|---|---|---|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {path} | {label} | {stage} | {n_regular} | {n_inner} | {physical_active} | {dominant} | "
            "{patch} | {regular_R} | {regular_E} | {outer_R} | {far_omega} | {D} | {C1} | {C2} | {K} | "
            "{Rson_rg} | {delta_Rson_rg} | {lambda0} | {delta_lambda0} | {int_adv} | {delta_int_adv} | "
            "{local_splits} | {local_defect_max} | {nfev} | {success} | {message} |".format(
                path=row["path"],
                label=row["label"],
                stage=row["stage"],
                n_regular=row["n_regular"],
                n_inner=row["n_inner"],
                physical_active=fmt(float(row["physical_active"])),
                dominant=row["dominant"],
                patch=fmt(float(row["patch"])),
                regular_R=fmt(float(row["regular_R"])),
                regular_E=fmt(float(row["regular_E"])),
                outer_R=fmt(float(row["outer_R"])),
                far_omega=fmt(float(row["far_omega"])),
                D=fmt(float(row["D"])),
                C1=fmt(float(row["C1"])),
                C2=fmt(float(row["C2"])),
                K=fmt(float(row["K"])),
                Rson_rg=fmt(float(row["Rson_rg"])),
                delta_Rson_rg=fmt(float(row["delta_Rson_rg"])),
                lambda0=fmt(float(row["lambda0"])),
                delta_lambda0=fmt(float(row["delta_lambda0"])),
                int_adv=fmt(float(row["int_adv"])),
                delta_int_adv=fmt(float(row["delta_int_adv"])),
                local_splits=row.get("local_splits", 0),
                local_defect_max=fmt(float(row.get("local_defect_max", np.nan))),
                nfev=row["nfev"],
                success="yes" if row["success"] else "no",
                message=str(row["message"]).replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")


def run_path(
    path_label: str,
    targets: tuple[int, ...],
    start_x: np.ndarray,
    start_params,
    g_s: np.ndarray,
    ratio: float,
    fiducial: FiducialParams,
    mdot_edd: float,
    ref_row: dict[str, float],
    ref_arrays: dict[str, np.ndarray],
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    current_x = start_x
    current_params = start_params
    for n_regular in targets:
        target_params = make_buffer_params(fiducial, ratio, mdot_edd, n_regular, current_params.n_outer, current_params.R_far_rg, current_params.delta_s)
        seed, stats = buffer_to_buffer_seed(current_x, current_params, target_params, "defect_preserving")
        label = f"{path_label}_Nreg{n_regular}"
        seed_row = buffer_row_with_reference(buffer_audit(label, seed, target_params, g_s), ref_row, ref_arrays, target_params)
        attach_stage(seed_row, label, "seed", "defect_preserving", stats)
        seed_row["path"] = path_label
        rows.append(seed_row)
        print(
            f"{path_label} Nreg{n_regular} seed physical={seed_row['physical_active']:.3e} "
            f"dominant={seed_row['dominant']} local={stats['local_defect_max']:.3e}",
            flush=True,
        )

        release = solve_buffer(seed, target_params, g_s, MAX_NFEV_BUFFER_RELEASE)
        release_row = buffer_row_with_reference(buffer_audit(label, release.x, target_params, g_s, release), ref_row, ref_arrays, target_params)
        attach_stage(release_row, label, "release", "defect_preserving", stats)
        release_row["path"] = path_label
        rows.append(release_row)
        print(
            f"{path_label} Nreg{n_regular} release physical={release_row['physical_active']:.3e} "
            f"dominant={release_row['dominant']} nfev={release.nfev}",
            flush=True,
        )

        polish = solve_buffer(release.x, target_params, g_s, MAX_NFEV_BUFFER_POLISH)
        polish_row = buffer_row_with_reference(buffer_audit(label, polish.x, target_params, g_s, polish), ref_row, ref_arrays, target_params)
        attach_stage(polish_row, label, "polish", "defect_preserving", stats)
        polish_row["path"] = path_label
        rows.append(polish_row)
        print(
            f"{path_label} Nreg{n_regular} polish physical={polish_row['physical_active']:.3e} "
            f"dominant={polish_row['dominant']} nfev={polish.nfev}",
            flush=True,
        )
        save_checkpoint(label, np.asarray(polish_row["x"], dtype=float), polish_row)
        current_x = np.asarray(polish_row["x"], dtype=float)
        current_params = target_params
        if float(polish_row["physical_active"]) > GATE_LIMIT:
            break
    return rows


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    source_x, source_meta = load_checkpoint(SOURCE_CHECKPOINT)
    ratio = float(source_meta["ratio"])
    source_params = make_params(
        fiducial,
        ratio,
        mdot_edd,
        int(source_meta["n_inner"]),
        int(source_meta["n_outer"]),
        float(source_meta["R_far_rg"]),
    )
    ref_arrays = combined_profile_arrays(source_x, source_params)
    source_row = {
        "Rson_rg": float(source_meta["Rson_rg"]),
        "lambda0": float(source_meta["lambda0"]),
        "int_adv": float(source_meta["int_adv"]),
    }
    g_s = source_first_slope(source_x, source_params)
    best_x, best_meta = load_row(BEST_BUFFER_CHECKPOINT)
    start_params = make_buffer_params(
        fiducial,
        ratio,
        mdot_edd,
        int(best_meta["n_regular"]),
        int(best_meta["n_outer"]),
        float(best_meta["R_far_rg"]),
        float(best_meta["delta_s"]),
    )
    rows: list[dict[str, object]] = []
    rows.extend(
        run_path(
            "direct64to128",
            DIRECT_TARGETS,
            best_x,
            start_params,
            g_s,
            ratio,
            fiducial,
            mdot_edd,
            source_row,
            ref_arrays,
        )
    )
    rows.extend(
        run_path(
            "staged64to96to128",
            STAGED_TARGETS,
            best_x,
            start_params,
            g_s,
            ratio,
            fiducial,
            mdot_edd,
            source_row,
            ref_arrays,
        )
    )
    write_table(rows)
    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
