#!/usr/bin/env python3
"""Freeze the conservative recovery-surface and guard-buffer contract."""
from pathlib import Path
import csv,hashlib,json,sys
ROOT=Path(__file__).resolve().parents[1]
for p in (ROOT/"src",ROOT/"scripts"):
    if str(p) not in sys.path:sys.path.insert(0,str(p))
import run_causal_inner_fine_complement_spatial_decay_audit_wp10c9d6c7c3b5c4f7 as c4f7  # noqa:E402
SCHEMA_VERSION=1;WORK_PACKAGE="WP10c9d6c7c3b5c4f8";ARTIFACT="causal_inner_recovered_coupling_control_volume_manifest_wp10c9d6c7c3b5c4f8";THIS_RUNNER="scripts/run_causal_inner_recovered_coupling_control_volume_manifest_wp10c9d6c7c3b5c4f8.py";THIS_TEST="tests/test_causal_inner_recovered_coupling_control_volume_manifest_wp10c9d6c7c3b5c4f8.py"
REPORT_RELATIVE="docs/reports/current/CODEX_CAUSAL_INNER_RECOVERED_COUPLING_CONTROL_VOLUME_MANIFEST_WP10C9D6C7C3B5C4F8_2026-08-13.md";REPORT_PATH=ROOT/REPORT_RELATIVE;CANONICAL_DIRECTORY=ROOT/"results/canonical"/ARTIFACT;CONFIG_PATH=CANONICAL_DIRECTORY/"config.json";MANIFEST_PATH=CANONICAL_DIRECTORY/"control_volume_manifest.json";SUMMARY_PATH=CANONICAL_DIRECTORY/"summary.json";PROVENANCE_PATH=CANONICAL_DIRECTORY/"provenance.json";CANONICAL_MANIFEST=ROOT/"results/manifests/canonical_artifacts.csv";CANONICAL_SUMMARY=ROOT/"results/manifests/canonical_summary.json"
RECOVERY_FACE=36;ORIGINAL_COUPLING_FACE=48;RECOVERY_RADIUS_RG=7.827912545605751;ORIGINAL_RADIUS_RG=12.777241939756358
def _read(p):return json.loads(p.read_text())
def _write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
def _sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def _manifest():return {'schema_version':1,'work_package':WORK_PACKAGE,'classification':'recovered_coupling_guard_buffer_manifest_frozen_analysis_only_ledger_audit_authorized','definitions_only':True,'new_trajectory':False,'recovery_parent_face':RECOVERY_FACE,'recovery_radius_rg':RECOVERY_RADIUS_RG,'original_coupling_parent_face':ORIGINAL_COUPLING_FACE,'original_coupling_radius_rg':ORIGINAL_RADIUS_RG,'guard_buffer_parent_cells':(RECOVERY_FACE,ORIGINAL_COUPLING_FACE),'guard_buffer_remains_explicitly_evolved':True,'recovery_flux_is_not_relabelled_horizon_or_original_coupling_flux':True,'candidate_architectures':{'overlap_state':{'slow_boundary_flux':'shared_M_J_E_flux_at_recovery_face_36','retained_guard_state':'complete_mapped_M_J_E_plus_responsive_height_BDF_history_in_cells_36_to_48','outer_use':'requires_overlap_or_reaction_ledger_no_direct_substitution'},'control_volume_identity':{'identity':'F_48_equals_F_36_plus_integrated_sources_minus_complete_storage_rate_over_36_to_48','mapped_storage_and_nonexact_height_history_both_required':True,'direct_BDF_identity_may_not_be_used_as_independent_convergence_evidence':True}},'analysis_contract':{'existing_states_only':True,'compare_direct_and_control_volume_face_48_flux':True,'separate_mapped_storage_rate_responsive_height_rate_and_all_stationary_source_blocks':True,'three_grid_instantaneous_cumulative_and_window_mean_forms':True,'test_recovery_faces':(32,36,40),'require_recovery_face_36_remain_spatially_convergent':True,'require_exact_buffer_ledger_closure':True},'decision':{'control_volume_absolute_export_converges':'authorize_Q3_memory_screen_using_augmented_guard_buffer_output_map','only_overlap_state_converges':'authorize_retained_guard_buffer_micro_macro_manifest','neither_converges':'absolute_slow_closure_remains_blocked','identity_is_only_discrete_tautology':'do_not_claim_recovery_run_independent_temporal_shadow_or_reformulate_output'},'response_certificate_preserved':True,'absolute_closure_fit_authorized':False,'memory_propagation_authorized':False,'fixed_Q_authorized':False,'reduced_slow_evolution_authorized':False,'hard_stops':('do_not_drop_guard_buffer_storage_or_sources','do_not_treat_direct_BDF_rearrangement_as_independent_validation','do_not_relabel_face_36_as_face_48_or_horizon_flux','do_not_run_new_trajectory_memory_or_fixed_Q'),'authorized_next':'WP10c9d6c7c3b5c4f9_recovered_coupling_existing_state_ledger_preflight'}
def _catalog(s):
 rows=[]
 if CANONICAL_MANIFEST.exists():
  with CANONICAL_MANIFEST.open(newline='') as h:rows=list(csv.DictReader(h))
 rows=[r for r in rows if r.get('case')!=ARTIFACT]
 for p in sorted(CANONICAL_DIRECTORY.iterdir()):
  if p.is_file():rows.append({'case':ARTIFACT,'path':str(p.relative_to(ROOT)),'bytes':str(p.stat().st_size),'sha256':_sha(p),'scientific_status':'PROSPECTIVE'})
 with CANONICAL_MANIFEST.open('w',newline='') as h:w=csv.DictWriter(h,fieldnames=['case','path','bytes','sha256','scientific_status'],lineterminator='\n');w.writeheader();w.writerows(rows)
 c=_read(CANONICAL_SUMMARY);c.setdefault('artifacts',{})[ARTIFACT]={'path':str(CANONICAL_DIRECTORY.relative_to(ROOT)),'classification':s['classification'],'passed':True};c.update({'case_count':len({r['case'] for r in rows}),'file_count':len(rows),'total_bytes':sum(int(r['bytes']) for r in rows),'latest_work_package':WORK_PACKAGE});_write(CANONICAL_SUMMARY,c)
def main():
 p=_read(c4f7.SUMMARY_PATH)
 if not p['passed'] or p['selected_recovery_parent_face']!=RECOVERY_FACE or p['authorized_next']!='definitions_only_recovered_coupling_control_volume_manifest':raise RuntimeError('c4f8 authorization changed')
 m=_manifest();s={'schema_version':1,'work_package':WORK_PACKAGE,'classification':m['classification'],'passed':True,'definitions_only':True,'selected_recovery_face_preserved':True,'new_trajectory_authorized':False,'memory_propagation_authorized':False,'fixed_Q_micro_solver_authorized':False,'reduced_slow_evolution_authorized':False,'physical_failure_detected':False,'authorized_next':m['authorized_next']};CANONICAL_DIRECTORY.mkdir(parents=True,exist_ok=True);_write(CONFIG_PATH,{'recovery_face':RECOVERY_FACE,'recovery_radius_rg':RECOVERY_RADIUS_RG,'guard_buffer_faces':(RECOVERY_FACE,ORIGINAL_COUPLING_FACE)});_write(MANIFEST_PATH,m);_write(SUMMARY_PATH,s);REPORT_PATH.parent.mkdir(parents=True,exist_ok=True);REPORT_PATH.write_text(f"# Recovered coupling control-volume manifest\n\nClassification: `{s['classification']}`.\n\nThe selected face is `{RECOVERY_FACE}` at `{RECOVERY_RADIUS_RG:.12f} rg`. Cells `{RECOVERY_FACE}:{ORIGINAL_COUPLING_FACE}` remain an explicit guard buffer. Face 36 is not relabelled as the original coupling or horizon flux.\n\nOnly an existing-state ledger preflight is authorized.\n");_write(PROVENANCE_PATH,{'parent_summary_sha256':_sha(c4f7.SUMMARY_PATH),'output_hashes':{}});(CANONICAL_DIRECTORY/'SHA256SUMS.txt').write_text(''.join(f"{_sha(x)}  {x.name}\n" for x in (CONFIG_PATH,MANIFEST_PATH,SUMMARY_PATH,PROVENANCE_PATH)));_catalog(s);print(json.dumps(s,indent=2))
if __name__=='__main__':main()
