"""Dense N=64 high-rate continuation with outer-boundary ramping."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    remap_profile_to_new_sonic_grid,
    solve_low_mdot_transonic_homotopy,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_n64_dense_high_rate.md"
RESIDUAL_TOL = 3.0e-4
R_OUT_RG = 3000.0
WARMUP_RATIOS = (1.0e-3, 2.5e-3, 5.0e-3, 1.0e-2, 2.0e-2, 3.0e-2)
N48_BRIDGE_RATIOS = (5.0e-2, 0.1, 0.2, 0.3)
N64_DENSE_RATIOS = (0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.715)
SONIC_WEIGHTS = (0.3, 1.0, 3.0)
OUTER_WEIGHTS = (0.3, 0.7)


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def dominant_block(audit) -> str:
    values = {
        "interval_R": abs(audit.interval_radial_max),
        "interval_E": abs(audit.interval_energy_max),
        "outer_Omega": abs(audit.outer_omega),
        "outer_E": abs(audit.outer_energy),
        "D": abs(audit.sonic_D),
        "C1": abs(audit.sonic_C1),
        "C2": abs(audit.sonic_C2),
    }
    return max(values, key=values.get)


def accepted_for_continuation(final) -> bool:
    status = final.status
    return bool(
        np.isfinite(final.max_residual)
        and final.max_residual <= RESIDUAL_TOL
        and status.optimizer_acceptable
        and status.equations_converged
        and status.sonic_regular
        and status.active_bounds_clear
        and status.positive_state
        and status.outer_thin
    )


def solve_one(
    *,
    M2_g: float,
    mdot_edd: float,
    alpha: float,
    ratio: float,
    n_nodes: int,
    R_out_rg: float,
    seed_profile,
    sonic_weight_sequence: tuple[float, ...],
    outer_weight_sequence: tuple[float, ...],
    max_nfev: int = 2000,
    max_nfev_per_stage: int = 900,
):
    params = TransonicSlimParams(
        M2_g=M2_g,
        Mdot_g_s=ratio * mdot_edd,
        alpha=alpha,
        n_nodes=n_nodes,
        R_out_rg=R_out_rg,
        max_nfev=max_nfev,
        residual_tol=RESIDUAL_TOL,
    )
    guess = remap_profile_to_new_sonic_grid(seed_profile, params) if seed_profile is not None else None
    result = solve_low_mdot_transonic_homotopy(
        params,
        initial_guess=guess,
        max_nfev_per_stage=max_nfev_per_stage,
        final_max_nfev=max_nfev,
        sonic_weight_sequence=sonic_weight_sequence,
        outer_weight_sequence=outer_weight_sequence,
    )
    return params, result


def row_from_result(label: str, ratio: float, n_nodes: int, params, result, seed: str) -> dict[str, object]:
    final = result.final_result
    profile = final.profile
    audit = final.residual_audit
    status = final.status
    b2_stages = [stage for stage in result.stages if stage.name.startswith("B2_")]
    b3_stages = [stage for stage in result.stages if stage.name.startswith("B3_")]
    return {
        "label": label,
        "seed": seed,
        "ratio": ratio,
        "n_nodes": n_nodes,
        "accepted": accepted_for_continuation(final),
        "physical": status.physically_valid,
        "optimizer_ok": status.optimizer_acceptable,
        "equations": status.equations_converged,
        "sonic": status.sonic_regular,
        "dominant": dominant_block(audit),
        "lambda_ratio": audit.lambda0_over_lK_isco,
        "Rson_rg": profile.sonic_radius / params.r_g,
        "max_HR": float(np.max(profile.H_over_R)),
        "outer_HR": audit.outer_H_over_R,
        "outer_Qadv_over_Qvisc": audit.outer_Qadv_over_Qvisc,
        "max_Qadv_over_Qvisc": float(np.max(np.abs(profile.Q_adv) / (np.abs(profile.Q_visc) + 1.0e-300))),
        "integrated_advective_fraction": profile.integrated_advective_fraction,
        "max_xi": float(np.max(profile.xi_eff)),
        "max_residual": final.max_residual,
        "interval_radial": audit.interval_radial_max,
        "interval_energy": audit.interval_energy_max,
        "outer_omega": audit.outer_omega,
        "outer_energy": audit.outer_energy,
        "sonic_D": audit.sonic_D,
        "sonic_C1": audit.sonic_C1,
        "sonic_C2": audit.sonic_C2,
        "stage_B2_last": b2_stages[-1].max_residual if b2_stages else np.nan,
        "stage_B3_last": b3_stages[-1].max_residual if b3_stages else np.nan,
        "nfev": final.nfev,
        "message": final.message,
    }


def write_table(rows: list[dict[str, object]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Dense N=64 High-Rate Continuation",
        "",
        "Generated by `scripts/run_transonic_n64_dense_high_rate.py`.",
        "",
        f"Configuration: `R_out={R_OUT_RG:g} r_g`, dense N64 stages use `outer_weight_sequence={OUTER_WEIGHTS}`.",
        "",
        "| label | seed | N | Mdot/Mdot_Edd | accepted | physical | opt ok | equations | sonic | dominant | lambda/lK_ISCO | R_son/r_g | max H/R | outer H/R | outer Qadv/Qvisc | max Qadv/Qvisc | int adv frac | max xi | max residual | interval R | interval E | outer Omega | outer E | D | C1 | C2 | B2 max | B3 max | nfev | message |",
        "|---|---|---:|---:|:---:|:---:|:---:|:---:|:---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {label} | {seed} | {n_nodes} | {ratio} | {accepted} | {physical} | {optimizer_ok} | "
            "{equations} | {sonic} | {dominant} | {lambda_ratio} | {Rson_rg} | {max_HR} | "
            "{outer_HR} | {outer_Qadv_over_Qvisc} | {max_Qadv_over_Qvisc} | "
            "{integrated_advective_fraction} | {max_xi} | {max_residual} | {interval_radial} | "
            "{interval_energy} | {outer_omega} | {outer_energy} | {sonic_D} | {sonic_C1} | "
            "{sonic_C2} | {stage_B2_last} | {stage_B3_last} | {nfev} | {message} |".format(
                label=row["label"],
                seed=row["seed"],
                n_nodes=row["n_nodes"],
                ratio=fmt(float(row["ratio"])),
                accepted="yes" if row["accepted"] else "no",
                physical="yes" if row["physical"] else "no",
                optimizer_ok="yes" if row["optimizer_ok"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                dominant=row["dominant"],
                lambda_ratio=fmt(float(row["lambda_ratio"])),
                Rson_rg=fmt(float(row["Rson_rg"])),
                max_HR=fmt(float(row["max_HR"])),
                outer_HR=fmt(float(row["outer_HR"])),
                outer_Qadv_over_Qvisc=fmt(float(row["outer_Qadv_over_Qvisc"])),
                max_Qadv_over_Qvisc=fmt(float(row["max_Qadv_over_Qvisc"])),
                integrated_advective_fraction=fmt(float(row["integrated_advective_fraction"])),
                max_xi=fmt(float(row["max_xi"])),
                max_residual=fmt(float(row["max_residual"])),
                interval_radial=fmt(float(row["interval_radial"])),
                interval_energy=fmt(float(row["interval_energy"])),
                outer_omega=fmt(float(row["outer_omega"])),
                outer_energy=fmt(float(row["outer_energy"])),
                sonic_D=fmt(float(row["sonic_D"])),
                sonic_C1=fmt(float(row["sonic_C1"])),
                sonic_C2=fmt(float(row["sonic_C2"])),
                stage_B2_last=fmt(float(row["stage_B2_last"])),
                stage_B3_last=fmt(float(row["stage_B3_last"])),
                nfev=row["nfev"],
                message=str(row["message"]).replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")


def append_row(rows: list[dict[str, object]], row: dict[str, object]) -> None:
    rows.append(row)
    write_table(rows)
    print(
        f"{row['label']} N={row['n_nodes']} rate={row['ratio']:.4g} "
        f"accepted={row['accepted']} max={row['max_residual']:.4g} "
        f"outer={row['outer_omega']:.4g} D={row['sonic_D']:.4g} dom={row['dominant']}",
        flush=True,
    )


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    rows: list[dict[str, object]] = []

    warmup_profile = None
    for ratio in WARMUP_RATIOS:
        params, result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=24,
            R_out_rg=1000.0,
            seed_profile=warmup_profile,
            sonic_weight_sequence=(1.0,),
            outer_weight_sequence=(),
            max_nfev=1800,
            max_nfev_per_stage=800,
        )
        row = row_from_result("warmup", ratio, 24, params, result, "previous")
        append_row(rows, row)
        if row["accepted"] or (result.final_result.status.sonic_regular and result.final_result.max_residual < 8.0e-4):
            warmup_profile = result.final_result.profile

    bridge_profile = warmup_profile
    for ratio in N48_BRIDGE_RATIOS:
        params, result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=48,
            R_out_rg=R_OUT_RG,
            seed_profile=bridge_profile,
            sonic_weight_sequence=SONIC_WEIGHTS,
            outer_weight_sequence=(),
        )
        row = row_from_result("bridge", ratio, 48, params, result, "previous")
        append_row(rows, row)
        if row["accepted"] or (result.final_result.status.sonic_regular and result.final_result.max_residual < 8.0e-4):
            bridge_profile = result.final_result.profile

    dense_profile = bridge_profile
    failures = 0
    for ratio in N64_DENSE_RATIOS:
        params, result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=64,
            R_out_rg=R_OUT_RG,
            seed_profile=dense_profile,
            sonic_weight_sequence=SONIC_WEIGHTS,
            outer_weight_sequence=OUTER_WEIGHTS,
            max_nfev=2200,
            max_nfev_per_stage=1000,
        )
        row = row_from_result("dense", ratio, 64, params, result, "previous")
        append_row(rows, row)
        if row["accepted"]:
            dense_profile = result.final_result.profile
            failures = 0
        else:
            failures += 1
            if failures >= 2:
                break

    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
