"""Resolution ladder for moderate/high-rate transonic homotopy solves."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    remap_profile_to_new_sonic_grid,
    solve_low_mdot_transonic_homotopy,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_resolution_ladder.md"


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def usable(status) -> bool:
    return bool(
        status.physically_valid
        or (
            status.optimizer_acceptable
            and status.equations_converged
            and status.sonic_regular
            and status.active_bounds_clear
            and status.outer_thin
        )
    )


def solve_sequence(M2_g: float, mdot_edd: float, alpha: float, n_nodes: int, R_out_rg: float, ratios):
    previous_profile = None
    rows = []
    for ratio in ratios:
        params = TransonicSlimParams(
            M2_g=M2_g,
            Mdot_g_s=ratio * mdot_edd,
            alpha=alpha,
            n_nodes=n_nodes,
            R_out_rg=R_out_rg,
            max_nfev=1600,
            residual_tol=3.0e-4,
        )
        guess = remap_profile_to_new_sonic_grid(previous_profile, params) if previous_profile is not None else None
        result = solve_low_mdot_transonic_homotopy(
            params,
            initial_guess=guess,
            max_nfev_per_stage=900,
            final_max_nfev=1600,
        )
        final = result.final_result
        profile = final.profile
        audit = final.residual_audit
        status = final.status
        is_usable = usable(status)
        rows.append(
            {
                "n_nodes": n_nodes,
                "R_out_rg": R_out_rg,
                "ratio": ratio,
                "usable": is_usable,
                "physical": status.physically_valid,
                "equations": status.equations_converged,
                "sonic": status.sonic_regular,
                "lambda_ratio": audit.lambda0_over_lK_isco,
                "Rson_rg": profile.sonic_radius / params.r_g,
                "max_HR": float(np.max(profile.H_over_R)),
                "outer_HR": audit.outer_H_over_R,
                "max_residual": final.max_residual,
                "interval_radial": audit.interval_radial_max,
                "interval_energy": audit.interval_energy_max,
                "outer_omega": audit.outer_omega,
                "outer_energy": audit.outer_energy,
                "sonic_D": audit.sonic_D,
                "sonic_C1": audit.sonic_C1,
                "sonic_C2": audit.sonic_C2,
                "nfev": final.nfev,
                "stage_A": result.stages[0].max_residual,
                "stage_B": result.stages[1].max_residual,
                "message": final.message,
            }
        )
        print(
            f"N={n_nodes} Rout={R_out_rg:g} rate={ratio:g} usable={is_usable} "
            f"max={final.max_residual:.4g} outer={audit.outer_omega:.4g} "
            f"radial={audit.interval_radial_max:.4g} sonic={audit.sonic_D:.4g} H/R={np.max(profile.H_over_R):.4g}",
            flush=True,
        )
        if is_usable or (status.sonic_regular and final.max_residual < 8.0e-4):
            previous_profile = profile
        elif ratio <= 3.0e-2:
            # If the warm-up branch fails badly, the high-rate rows are not comparable.
            break
    return rows


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    warmup = [1.0e-3, 2.5e-3, 5.0e-3, 1.0e-2, 2.0e-2, 3.0e-2]
    targets = [5.0e-2, 0.1]
    configs = [(24, 1000.0), (32, 1000.0), (48, 1000.0)]
    rows = []
    for n_nodes, R_out_rg in configs:
        rows.extend(solve_sequence(fiducial.M2_g, mdot_edd, fiducial.alpha_cool, n_nodes, R_out_rg, warmup + targets))

    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Transonic Resolution Ladder",
        "",
        "Generated by `scripts/run_transonic_resolution_ladder.py`.",
        "",
        "Each configuration warms up through the accepted low-rate branch before evaluating `0.05` and `0.1`.",
        "",
        "| N | R_out/r_g | Mdot/Mdot_Edd | usable | physical | equations | sonic | lambda/lK_ISCO | R_son/r_g | max H/R | outer H/R | max residual | interval R | interval E | outer Omega | outer E | D | C1 | C2 | nfev | stage A | stage B | message |",
        "|---:|---:|---:|:---:|:---:|:---:|:---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {n_nodes} | {R_out_rg} | {ratio} | {usable} | {physical} | {equations} | {sonic} | "
            "{lambda_ratio} | {Rson_rg} | {max_HR} | {outer_HR} | {max_residual} | "
            "{interval_radial} | {interval_energy} | {outer_omega} | {outer_energy} | "
            "{sonic_D} | {sonic_C1} | {sonic_C2} | {nfev} | {stage_A} | {stage_B} | {message} |".format(
                n_nodes=row["n_nodes"],
                R_out_rg=fmt(row["R_out_rg"]),
                ratio=fmt(row["ratio"]),
                usable="yes" if row["usable"] else "no",
                physical="yes" if row["physical"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                lambda_ratio=fmt(row["lambda_ratio"]),
                Rson_rg=fmt(row["Rson_rg"]),
                max_HR=fmt(row["max_HR"]),
                outer_HR=fmt(row["outer_HR"]),
                max_residual=fmt(row["max_residual"]),
                interval_radial=fmt(row["interval_radial"]),
                interval_energy=fmt(row["interval_energy"]),
                outer_omega=fmt(row["outer_omega"]),
                outer_energy=fmt(row["outer_energy"]),
                sonic_D=fmt(row["sonic_D"]),
                sonic_C1=fmt(row["sonic_C1"]),
                sonic_C2=fmt(row["sonic_C2"]),
                nfev=row["nfev"],
                stage_A=fmt(row["stage_A"]),
                stage_B=fmt(row["stage_B"]),
                message=row["message"].replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
