"""Grid, clustering, and outer-boundary audit for the transonic homotopy solver."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    remap_profile_to_new_sonic_grid,
    solve_low_mdot_transonic_homotopy,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_grid_convergence.md"


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def usable(status) -> bool:
    return bool(
        status.physically_valid
        or (
            status.optimizer_acceptable
            and status.equations_converged
            and status.sonic_regular
            and status.thin_limit_ok
            and status.active_bounds_clear
            and status.outer_thin
        )
    )


def run_config(M2_g: float, mdot_edd: float, alpha: float, n_nodes: int, R_out_rg: float, grid_power: float):
    ratios = [1.0e-3, 2.5e-3, 4.5e-3, 5.5e-3, 1.0e-2]
    previous_profile = None
    rows = []
    for ratio in ratios:
        params = TransonicSlimParams(
            M2_g=M2_g,
            Mdot_g_s=ratio * mdot_edd,
            alpha=alpha,
            n_nodes=n_nodes,
            R_out_rg=R_out_rg,
            grid_power=grid_power,
            max_nfev=1200,
            residual_tol=3.0e-4,
        )
        guess = remap_profile_to_new_sonic_grid(previous_profile, params) if previous_profile is not None else None
        result = solve_low_mdot_transonic_homotopy(
            params,
            initial_guess=guess,
            max_nfev_per_stage=700,
            final_max_nfev=1200,
        )
        final = result.final_result
        profile = final.profile
        audit = final.residual_audit
        status = final.status
        is_usable = usable(status)
        rows.append(
            {
                "n_nodes": n_nodes,
                "R_out_rg": R_out_rg,
                "grid_power": grid_power,
                "ratio": ratio,
                "usable": is_usable,
                "physical": status.physically_valid,
                "equations": status.equations_converged,
                "sonic": status.sonic_regular,
                "lambda_ratio": audit.lambda0_over_lK_isco,
                "Rson_rg": profile.sonic_radius / params.r_g,
                "max_HR": float(np.max(profile.H_over_R)),
                "max_residual": final.max_residual,
                "interval_radial": audit.interval_radial_max,
                "interval_energy": audit.interval_energy_max,
                "outer_omega": audit.outer_omega,
                "outer_energy": audit.outer_energy,
                "sonic_D": audit.sonic_D,
                "sonic_C1": audit.sonic_C1,
                "sonic_C2": audit.sonic_C2,
                "nfev": final.nfev,
                "message": final.message,
            }
        )
        print(
            f"N={n_nodes} Rout={R_out_rg:g} p={grid_power:g} ratio={ratio:g} "
            f"usable={is_usable} max={final.max_residual:.4g} outer={audit.outer_omega:.4g} "
            f"radial={audit.interval_radial_max:.4g}",
            flush=True,
        )
        seed_ok = is_usable or (
            status.sonic_regular
            and status.thin_limit_ok
            and final.max_residual < 6.0e-4
        )
        if seed_ok:
            previous_profile = profile
        elif final.max_residual > 1.0e-2:
            break
    return rows


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    configs = [
        (18, 300.0, 1.0),
        (24, 300.0, 1.0),
        (24, 300.0, 1.5),
        (24, 1000.0, 1.0),
    ]
    rows = []
    for n_nodes, R_out_rg, grid_power in configs:
        rows.extend(run_config(fiducial.M2_g, mdot_edd, fiducial.alpha_cool, n_nodes, R_out_rg, grid_power))

    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Transonic Grid and Outer-Boundary Convergence Audit",
        "",
        "Generated by `scripts/run_transonic_grid_convergence.py`.",
        "",
        "| N | R_out/r_g | grid p | Mdot/Mdot_Edd | usable | physical | equations | sonic | lambda/lK_ISCO | R_son/r_g | max H/R | max residual | interval R | interval E | outer Omega | outer E | D | C1 | C2 | nfev | message |",
        "|---:|---:|---:|---:|:---:|:---:|:---:|:---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {n_nodes} | {R_out_rg} | {grid_power} | {ratio} | {usable} | {physical} | "
            "{equations} | {sonic} | {lambda_ratio} | {Rson_rg} | {max_HR} | {max_residual} | "
            "{interval_radial} | {interval_energy} | {outer_omega} | {outer_energy} | "
            "{sonic_D} | {sonic_C1} | {sonic_C2} | {nfev} | {message} |".format(
                n_nodes=row["n_nodes"],
                R_out_rg=fmt(row["R_out_rg"]),
                grid_power=fmt(row["grid_power"]),
                ratio=fmt(row["ratio"]),
                usable="yes" if row["usable"] else "no",
                physical="yes" if row["physical"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                lambda_ratio=fmt(row["lambda_ratio"]),
                Rson_rg=fmt(row["Rson_rg"]),
                max_HR=fmt(row["max_HR"]),
                max_residual=fmt(row["max_residual"]),
                interval_radial=fmt(row["interval_radial"]),
                interval_energy=fmt(row["interval_energy"]),
                outer_omega=fmt(row["outer_omega"]),
                outer_energy=fmt(row["outer_energy"]),
                sonic_D=fmt(row["sonic_D"]),
                sonic_C1=fmt(row["sonic_C1"]),
                sonic_C2=fmt(row["sonic_C2"]),
                nfev=row["nfev"],
                message=row["message"].replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
