#!/usr/bin/env python3
"""Diagnose the nonreturning complete-cycle trajectory without truth calls.

This package consumes only the committed WP10c9d6c7c3b5c4f25fe trajectory and
exact-witness arrays.  It decides whether those data support a cycle closure,
an equilibrium closure, or a wider autonomous arclength continuation.  It
does not evaluate the physical field, retract a new state, or advance time.
"""

from __future__ import annotations

import argparse
import csv
import inspect
import json
from pathlib import Path
import platform
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
for path in (ROOT / "src", ROOT / "scripts"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import run_causal_inner_adaptive_complete_cycle_execution_wp10c9d6c7c3b5c4f25fe as parent  # noqa: E402


SCHEMA_VERSION = 1
WORK_PACKAGE = "WP10c9d6c7c3b5c4f25fg"
CLASSIFICATION = (
    "autonomous_open_low_curvature_transient_wide_arclength_transport_supported"
)
ARTIFACT = (
    "causal_inner_complete_cycle_asymptotic_path_diagnosis_"
    "wp10c9d6c7c3b5c4f25fg"
)
CANONICAL_DIRECTORY = ROOT / "results/canonical" / ARTIFACT
REPORT_RELATIVE = (
    "docs/reports/current/CODEX_CAUSAL_INNER_COMPLETE_CYCLE_ASYMPTOTIC_PATH_"
    "DIAGNOSIS_WP10C9D6C7C3B5C4F25FG_2026-08-23.md"
)
REPORT_PATH = ROOT / REPORT_RELATIVE
THIS_RUNNER = (
    "scripts/run_causal_inner_complete_cycle_asymptotic_path_diagnosis_"
    "wp10c9d6c7c3b5c4f25fg.py"
)
THIS_TEST = (
    "tests/test_causal_inner_complete_cycle_asymptotic_path_diagnosis_"
    "wp10c9d6c7c3b5c4f25fg.py"
)
AUTHORIZED_NEXT = (
    "WP10c9d6c7c3b5c4f25fh_curvature_adaptive_arclength_continuation_manifest"
)

MACRO_STEP_SECONDS = 2.5e-4
HERMITE_STRIDES = (2, 4, 8, 16)
MAXIMUM_HERMITE_COORDINATE_DEFECT = 1.0e-2
MAXIMUM_HERMITE_RATE_DEFECT = 2.0e-2
MAXIMUM_OPEN_PATH_TORTUOSITY = 1.05
MINIMUM_FIRST_POD_ENERGY = 0.98
MINIMUM_START_DIRECTION_COSINE = 0.90
MINIMUM_OPEN_TERMINAL_SPEED_RATIO = 0.50
MAXIMUM_EQUILIBRIUM_TERMINAL_SPEED_RATIO = 0.10
MAXIMUM_CYCLE_RETURN_DISTANCE_FRACTION = 0.10


def _helper():
    return parent._helper()


def _validate_parent(*, require_clean: bool) -> dict:
    helper = _helper()
    hashes = helper._validate_checksums(parent.CANONICAL_DIRECTORY)
    summary = helper._read(parent.CANONICAL_DIRECTORY / "summary.json")
    metrics = helper._read(
        parent.CANONICAL_DIRECTORY / "cycle_execution_metrics.json"
    )
    values = metrics["gate_values"]
    if (
        summary["classification"] != parent.BUDGET_CLASSIFICATION
        or summary["passed"]
        or summary["complete_cycle_observed"]
        or summary["authorized_next"] is not None
        or values["completed_patches"] != 64
        or values["exact_free_field_witnesses"] != 192
        or values["cycle_observed"]
        or metrics["fixed_Q_physical_rate_calls"] != 0
        or metrics["fixed_Q_reaction_calls"] != 0
        or metrics["nonlinear_roots"] != 0
        or metrics["BDF_microsteps"] != 0
    ):
        raise RuntimeError("complete-cycle budget result changed")
    if require_clean and helper._git("status", "--short", "--untracked-files=no"):
        raise RuntimeError("asymptotic diagnosis requires a clean tracked tree")
    return {"hashes": hashes, "summary": summary, "metrics": metrics}


def _source_audit() -> dict:
    rate_source = parent.arclength._source()._post().exact_rate.rate_source
    evaluator = rate_source.causal_five_field_monolithic_frozen_tangent
    parameter_names = tuple(inspect.signature(evaluator).parameters)
    external_clock_names = {
        "time",
        "time_seconds",
        "phase",
        "forcing_phase",
        "orbital_phase",
    }
    source = (ROOT / parent.THIS_RUNNER).read_text(encoding="utf-8")
    return {
        "truth_evaluator": (
            "causal_five_field_monolithic_frozen_tangent"
        ),
        "truth_parameter_names": list(parameter_names),
        "external_clock_argument_present": bool(
            external_clock_names.intersection(parameter_names)
        ),
        "rom_forcing_angular_frequency_zero": (
            "forcing_angular_frequency=0.0" in source
        ),
        "truth_field_autonomous": bool(
            not external_clock_names.intersection(parameter_names)
            and "forcing_angular_frequency=0.0" in source
        ),
        "interpretation": (
            "any recurrence in the executed model must be generated by the "
            "autonomous physical state; no external clock was supplied"
        ),
    }


def _hermite_replay(
    coordinates: np.ndarray,
    rates: np.ndarray,
    stride: int,
) -> tuple[dict, dict[str, np.ndarray]]:
    x = np.asarray(coordinates, dtype=float)
    f = np.asarray(rates, dtype=float)
    selected_stride = int(stride)
    coordinate_defects = []
    rate_defects = []
    window_starts = []
    sample_indices = []
    for start in range(len(x) - selected_stride):
        stop = start + selected_stride
        duration = selected_stride * MACRO_STEP_SECONDS
        displacement_norm = max(
            float(np.linalg.norm(x[stop] - x[start])),
            np.finfo(float).tiny,
        )
        for sample in range(start + 1, stop):
            phase = (sample - start) / selected_stride
            h00 = 2.0 * phase**3 - 3.0 * phase**2 + 1.0
            h10 = phase**3 - 2.0 * phase**2 + phase
            h01 = -2.0 * phase**3 + 3.0 * phase**2
            h11 = phase**3 - phase**2
            prediction = (
                h00 * x[start]
                + h10 * duration * f[start]
                + h01 * x[stop]
                + h11 * duration * f[stop]
            )
            dh00 = 6.0 * phase**2 - 6.0 * phase
            dh10 = 3.0 * phase**2 - 4.0 * phase + 1.0
            dh01 = -6.0 * phase**2 + 6.0 * phase
            dh11 = 3.0 * phase**2 - 2.0 * phase
            rate_prediction = (
                dh00 * x[start]
                + dh10 * duration * f[start]
                + dh01 * x[stop]
                + dh11 * duration * f[stop]
            ) / duration
            coordinate_defects.append(
                np.linalg.norm(prediction - x[sample]) / displacement_norm
            )
            rate_defects.append(
                np.linalg.norm(rate_prediction - f[sample])
                / max(float(np.linalg.norm(f[sample])), np.finfo(float).tiny)
            )
            window_starts.append(start)
            sample_indices.append(sample)
    coordinate_array = np.asarray(coordinate_defects)
    rate_array = np.asarray(rate_defects)
    metrics = {
        "stride": selected_stride,
        "duration_seconds": selected_stride * MACRO_STEP_SECONDS,
        "sample_count": int(len(coordinate_array)),
        "maximum_coordinate_defect": float(np.max(coordinate_array)),
        "maximum_rate_defect": float(np.max(rate_array)),
        "p95_coordinate_defect": float(np.quantile(coordinate_array, 0.95)),
        "p95_rate_defect": float(np.quantile(rate_array, 0.95)),
        "passed": bool(
            np.max(coordinate_array) <= MAXIMUM_HERMITE_COORDINATE_DEFECT
            and np.max(rate_array) <= MAXIMUM_HERMITE_RATE_DEFECT
        ),
    }
    arrays = {
        "coordinate_defects": coordinate_array,
        "rate_defects": rate_array,
        "window_starts": np.asarray(window_starts, dtype=int),
        "sample_indices": np.asarray(sample_indices, dtype=int),
    }
    return metrics, arrays


def _linear_target_forecast(
    time_seconds: np.ndarray,
    values: np.ndarray,
    target: float,
    count: int,
) -> dict:
    t = np.asarray(time_seconds, dtype=float)[-count:]
    y = np.asarray(values, dtype=float)[-count:]
    slope, intercept = np.polyfit(t, y, 1)
    crossing = None
    if slope != 0.0:
        candidate = float((target - intercept) / slope)
        if candidate > float(t[-1]):
            crossing = candidate
    return {
        "sample_count": int(count),
        "slope_per_second": float(slope),
        "forecast_target_time_seconds": crossing,
        "forecast_additional_seconds": (
            None if crossing is None else crossing - float(t[-1])
        ),
    }


def _evaluate(parent_lock: dict) -> tuple[dict, dict[str, np.ndarray]]:
    helper = _helper()
    cycle = helper._load_npz(
        parent.CANONICAL_DIRECTORY / "cycle_execution_arrays.npz"
    )
    witnesses = helper._load_npz(
        parent.CANONICAL_DIRECTORY / "exact_witness_arrays.npz"
    )
    trajectory = np.asarray(cycle["trajectory_coordinates"], dtype=float)
    macro = np.asarray(cycle["trajectory_macro82"], dtype=float)
    section_normal = np.asarray(cycle["section_normal470"], dtype=float)
    anchor_mask = np.asarray(witnesses["kinds"]).astype(str) == "anchor"
    anchor_coordinates = np.asarray(witnesses["coordinates"])[anchor_mask]
    anchor_rates = np.asarray(witnesses["coordinate_rates_per_s"])[anchor_mask]
    np.testing.assert_array_equal(anchor_coordinates, trajectory[:-1])
    if trajectory.shape != (65, 470) or anchor_rates.shape != (64, 470):
        raise RuntimeError("canonical complete-cycle trajectory shape changed")

    anchor_time = MACRO_STEP_SECONDS * np.arange(len(anchor_rates), dtype=float)
    trajectory_time = MACRO_STEP_SECONDS * np.arange(len(trajectory), dtype=float)
    section = (trajectory - trajectory[0]) @ section_normal
    section_velocity = anchor_rates @ section_normal
    speeds = np.linalg.norm(anchor_rates, axis=1)
    unit_rates = anchor_rates / speeds[:, None]
    start_direction_cosines = unit_rates @ unit_rates[0]
    consecutive_cosines = np.sum(unit_rates[1:] * unit_rates[:-1], axis=1)
    consecutive_turns = np.arccos(np.clip(consecutive_cosines, -1.0, 1.0))
    displacement = trajectory - trajectory[0]
    increments = np.diff(trajectory, axis=0)
    path_length = float(np.sum(np.linalg.norm(increments, axis=1)))
    endpoint_distance = float(np.linalg.norm(displacement[-1]))
    tortuosity = path_length / max(endpoint_distance, np.finfo(float).tiny)
    centered = displacement - np.mean(displacement, axis=0)
    singular_values = np.linalg.svd(centered, compute_uv=False)
    pod_energy = singular_values**2 / np.sum(singular_values**2)
    terminal_speed_ratio = float(speeds[-1] / speeds[0])
    cycle_return_fraction = float(
        np.min(np.linalg.norm(displacement[2:], axis=1))
        / max(path_length, np.finfo(float).tiny)
    )

    hermite_metrics = {}
    hermite_arrays = {}
    for stride in HERMITE_STRIDES:
        item, arrays = _hermite_replay(anchor_coordinates, anchor_rates, stride)
        hermite_metrics[str(stride)] = item
        for name, value in arrays.items():
            hermite_arrays[f"stride_{stride}__{name}"] = value
    passing_strides = [
        stride for stride in HERMITE_STRIDES if hermite_metrics[str(stride)]["passed"]
    ]
    maximum_passing_stride = max(passing_strides, default=0)

    open_path_gates = {
        "section_strictly_increasing": bool(np.all(np.diff(section) > 0.0)),
        "section_velocity_strictly_positive": bool(
            np.all(section_velocity > 0.0)
        ),
        "path_tortuosity": tortuosity,
        "path_tortuosity_passed": bool(tortuosity <= MAXIMUM_OPEN_PATH_TORTUOSITY),
        "first_pod_energy": float(pod_energy[0]),
        "first_pod_energy_passed": bool(
            pod_energy[0] >= MINIMUM_FIRST_POD_ENERGY
        ),
        "minimum_start_direction_cosine": float(np.min(start_direction_cosines)),
        "direction_alignment_passed": bool(
            np.min(start_direction_cosines) >= MINIMUM_START_DIRECTION_COSINE
        ),
        "terminal_speed_ratio": terminal_speed_ratio,
        "terminal_speed_remains_finite": bool(
            terminal_speed_ratio >= MINIMUM_OPEN_TERMINAL_SPEED_RATIO
        ),
        "maximum_validated_hermite_stride": int(maximum_passing_stride),
        "four_millisecond_transport_passed": bool(maximum_passing_stride >= 16),
    }
    open_path_supported = bool(
        all(
            (
                open_path_gates["section_strictly_increasing"],
                open_path_gates["section_velocity_strictly_positive"],
                open_path_gates["path_tortuosity_passed"],
                open_path_gates["first_pod_energy_passed"],
                open_path_gates["direction_alignment_passed"],
                open_path_gates["terminal_speed_remains_finite"],
                open_path_gates["four_millisecond_transport_passed"],
            )
        )
    )
    equilibrium_supported = bool(
        terminal_speed_ratio <= MAXIMUM_EQUILIBRIUM_TERMINAL_SPEED_RATIO
        and np.all(np.diff(speeds[-16:]) < 0.0)
    )
    cycle_supported = bool(
        parent_lock["summary"]["complete_cycle_observed"]
        and cycle_return_fraction <= MAXIMUM_CYCLE_RETURN_DISTANCE_FRACTION
    )
    source_audit = _source_audit()
    passed = bool(
        source_audit["truth_field_autonomous"]
        and open_path_supported
        and not cycle_supported
        and not equilibrium_supported
    )
    classification = CLASSIFICATION if passed else (
        "complete_cycle_asymptotic_architecture_remains_unresolved"
    )

    angle_from_start = np.arccos(np.clip(start_direction_cosines, -1.0, 1.0))
    forecasts = {
        "section_velocity_zero": [
            _linear_target_forecast(anchor_time, section_velocity, 0.0, count)
            for count in (16, 32, 64)
        ],
        "direction_orthogonal_to_start": [
            _linear_target_forecast(
                anchor_time, angle_from_start, 0.5 * np.pi, count
            )
            for count in (16, 32, 64)
        ],
    }
    metrics = {
        "schema_version": SCHEMA_VERSION,
        "work_package": WORK_PACKAGE,
        "classification": classification,
        "passed": passed,
        "source_audit": source_audit,
        "open_path_gates": open_path_gates,
        "cycle_closure_supported": cycle_supported,
        "equilibrium_closure_supported": equilibrium_supported,
        "wide_arclength_transport_supported": open_path_supported,
        "hermite_replay": hermite_metrics,
        "forecasts_are_diagnostic_only": True,
        "linear_forecasts": forecasts,
        "gate_values": {
            "trajectory_duration_seconds": float(trajectory_time[-1]),
            "trajectory_points": int(len(trajectory)),
            "exact_anchor_rates": int(len(anchor_rates)),
            "section_endpoint": float(section[-1]),
            "minimum_section_increment": float(np.min(np.diff(section))),
            "minimum_section_velocity_per_second": float(
                np.min(section_velocity)
            ),
            "initial_speed_per_second": float(speeds[0]),
            "terminal_speed_per_second": float(speeds[-1]),
            "terminal_speed_ratio": terminal_speed_ratio,
            "minimum_start_direction_cosine": float(
                np.min(start_direction_cosines)
            ),
            "net_direction_turn_radians": float(angle_from_start[-1]),
            "cumulative_direction_turn_radians": float(
                np.sum(consecutive_turns)
            ),
            "path_length": path_length,
            "endpoint_distance": endpoint_distance,
            "path_tortuosity": tortuosity,
            "first_pod_energy": float(pod_energy[0]),
            "second_pod_energy": float(pod_energy[1]),
            "cycle_return_distance_fraction": cycle_return_fraction,
            "maximum_validated_hermite_stride": int(maximum_passing_stride),
            "maximum_validated_hermite_duration_seconds": (
                maximum_passing_stride * MACRO_STEP_SECONDS
            ),
            "fixed_Q_calls": 0,
            "new_exact_free_field_calls": 0,
            "new_retractions": 0,
            "new_physical_time_advanced_seconds": 0.0,
        },
        "input_lock": {
            "parent_hashes": parent_lock["hashes"],
            "parent_classification": parent_lock["summary"]["classification"],
        },
    }
    arrays = {
        "trajectory_time_seconds": trajectory_time,
        "anchor_time_seconds": anchor_time,
        "section": section,
        "section_velocity_per_second": section_velocity,
        "anchor_speed_per_second": speeds,
        "start_direction_cosine": start_direction_cosines,
        "consecutive_direction_turn_radians": consecutive_turns,
        "trajectory_singular_values": singular_values,
        "trajectory_pod_energy": pod_energy,
        "trajectory_macro82": macro,
        **hermite_arrays,
    }
    return metrics, arrays


def _architecture(metrics: dict) -> dict:
    stride = metrics["gate_values"]["maximum_validated_hermite_stride"]
    return {
        "schema_version": SCHEMA_VERSION,
        "work_package": WORK_PACKAGE,
        "selected_architecture": (
            "autonomous_curvature_adaptive_arclength_hermite_continuation"
        ),
        "truth_system": {
            "equation": "dy/dt=f_free(y)",
            "autonomous": True,
            "external_forcing_phase_added": False,
            "reason": (
                "the executed truth evaluator has no external clock argument; "
                "adding one would change rather than reduce the physical model"
            ),
        },
        "path_system": {
            "speed": "nu(y)=||f_free(y)||_2",
            "geometry": "dy/ds=f_free(y)/nu(y)",
            "clock": "dt/ds=1/nu(y)",
            "segment": (
                "cubic Hermite in physical coordinates from exact endpoint "
                "states and exact endpoint free rates"
            ),
            "maximum_prevalidated_span_seconds": stride * MACRO_STEP_SECONDS,
        },
        "adaptive_policy_for_next_manifest": {
            "initial_segment_seconds": 1.0e-3,
            "growth_factor_maximum": 2.0,
            "maximum_segment_seconds": 4.0e-3,
            "coordinate_defect_maximum": MAXIMUM_HERMITE_COORDINATE_DEFECT,
            "rate_defect_maximum": MAXIMUM_HERMITE_RATE_DEFECT,
            "exact_endpoint_before_propagation": True,
            "blind_exact_midpoint_every_nth_accepted_segment": 4,
            "failed_segment_is_never_propagated": True,
            "halve_on_defect_or_physical_failure": True,
        },
        "terminal_events": {
            "cycle": "same-orientation Poincare return with existing gates",
            "equilibrium": (
                "prospectively frozen small-speed plus stationary-residual and "
                "linear-stability certificate"
            ),
            "budget": "separate inconclusive classification",
        },
        "forbidden_shortcuts": [
            "fixed-Q physical clock",
            "fixed-Q reaction action",
            "unvalidated last-patch extrapolation",
            "invented periodic forcing",
            "cycle averaging before a return is observed",
        ],
        "authorization_boundary": (
            "definitions-only curvature-adaptive continuation manifest; neither "
            "cycle-map closure nor reduced slow evolution is authorized"
        ),
    }


def _save_npz(path: Path, arrays: dict[str, np.ndarray]) -> None:
    with path.open("wb") as handle:
        np.savez(handle, **arrays)


def _update_catalog(summary: dict) -> None:
    helper = _helper()
    cold = parent.manifest.parent.manifest.parent.arclength._source()._post().manifest.transition.manifest.cold.manifest
    with cold.CANONICAL_MANIFEST.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    rows = [row for row in rows if row.get("case") != ARTIFACT]
    for path in sorted(CANONICAL_DIRECTORY.iterdir()):
        if path.is_file():
            rows.append({
                "case": ARTIFACT,
                "path": str(path.relative_to(ROOT)),
                "bytes": str(path.stat().st_size),
                "sha256": helper._sha(path),
                "scientific_status": "SUPPORTED" if summary["passed"] else "REJECTED",
            })
    with cold.CANONICAL_MANIFEST.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=("case", "path", "bytes", "sha256", "scientific_status"),
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)
    catalog = helper._read(cold.CANONICAL_SUMMARY)
    catalog.setdefault("artifacts", {})[ARTIFACT] = {
        "path": str(CANONICAL_DIRECTORY.relative_to(ROOT)),
        "classification": summary["classification"],
        "passed": summary["passed"],
    }
    catalog.update({
        "case_count": len({row["case"] for row in rows}),
        "file_count": len(rows),
        "total_bytes": sum(int(row["bytes"]) for row in rows),
        "all_payload_hashes_recorded": True,
        "latest_source_parent_commit": helper._git("rev-parse", "HEAD"),
        "latest_work_package": WORK_PACKAGE,
    })
    helper._write_json(cold.CANONICAL_SUMMARY, catalog)


def _canonicalize(metrics: dict, arrays: dict[str, np.ndarray]) -> dict:
    helper = _helper()
    if CANONICAL_DIRECTORY.exists() or REPORT_PATH.exists():
        raise RuntimeError("asymptotic diagnosis result already exists")
    CANONICAL_DIRECTORY.mkdir(parents=True)
    helper._write_json(CANONICAL_DIRECTORY / "diagnosis_metrics.json", metrics)
    helper._write_json(
        CANONICAL_DIRECTORY / "mathematical_architecture_decision.json",
        _architecture(metrics),
    )
    _save_npz(CANONICAL_DIRECTORY / "diagnosis_arrays.npz", arrays)
    summary = {
        "schema_version": SCHEMA_VERSION,
        "work_package": WORK_PACKAGE,
        "classification": metrics["classification"],
        "passed": bool(metrics["passed"]),
        "cycle_closure_authorized": False,
        "equilibrium_closure_authorized": False,
        "wide_arclength_continuation_manifest_authorized": bool(metrics["passed"]),
        "reduced_slow_evolution_authorized": False,
        "authorized_next": AUTHORIZED_NEXT if metrics["passed"] else None,
    }
    helper._write_json(CANONICAL_DIRECTORY / "summary.json", summary)
    helper._write_json(CANONICAL_DIRECTORY / "provenance.json", {
        "runner": THIS_RUNNER,
        "test": THIS_TEST,
        "implementation_commit": helper._git("rev-parse", "HEAD"),
        "implementation_tree": helper._git("rev-parse", "HEAD^{tree}"),
        "source_hashes": {
            THIS_RUNNER: helper._sha(ROOT / THIS_RUNNER),
            THIS_TEST: helper._sha(ROOT / THIS_TEST),
            parent.THIS_RUNNER: helper._sha(ROOT / parent.THIS_RUNNER),
        },
        "python": sys.version,
        "numpy": np.__version__,
        "platform": platform.platform(),
    })
    names = sorted(path.name for path in CANONICAL_DIRECTORY.iterdir())
    (CANONICAL_DIRECTORY / "SHA256SUMS.txt").write_text(
        "".join(
            f"{helper._sha(CANONICAL_DIRECTORY / name)}  {name}\n"
            for name in names
        ),
        encoding="utf-8",
    )
    values = metrics["gate_values"]
    h16 = metrics["hermite_replay"]["16"]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(
        "\n".join((
            "# Complete-cycle asymptotic path diagnosis",
            "",
            f"Classification: `{metrics['classification']}`.",
            "",
            "The committed 16 ms original-free-field trajectory is an autonomous, open, low-curvature transient. Its Poincare section is strictly increasing, its path tortuosity is "
            f"`{values['path_tortuosity']:.6f}`, and its first POD direction contains `{values['first_pod_energy']:.6f}` of centered path energy.",
            "",
            f"The terminal speed remains `{values['terminal_speed_ratio']:.6f}` of its initial value and the net field-direction turn is only `{values['net_direction_turn_radians']:.6f}` rad. Neither a return cycle nor an equilibrium closure is supported.",
            "",
            f"Sliding cubic-Hermite replay over 4 ms spans has maximum coordinate defect `{h16['maximum_coordinate_defect']:.6e}` and rate defect `{h16['maximum_rate_defect']:.6e}`. This supports a definitions-only curvature-adaptive arclength continuation manifest with spans up to 4 ms.",
            "",
            "No new exact free-field evaluation, retraction, physical-time step, fixed-Q rate, reaction, nonlinear root, or BDF microstep was executed. Cycle averaging and reduced slow evolution remain unauthorized.",
            "",
        )),
        encoding="utf-8",
    )
    _update_catalog(summary)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", action="store_true")
    arguments = parser.parse_args()
    if not arguments.run:
        parser.error("--run is required")
    parent_lock = _validate_parent(require_clean=True)
    metrics, arrays = _evaluate(parent_lock)
    summary = _canonicalize(metrics, arrays)
    print(json.dumps(summary, indent=2, sort_keys=True))
    if not summary["passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
