#!/usr/bin/env python3
"""Freeze a bounded nonlinear relaxation-RK split microstep."""
from __future__ import annotations
import argparse,csv,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
for p in (ROOT/"src",ROOT/"scripts"):
 if str(p) not in sys.path:sys.path.insert(0,str(p))
import run_causal_inner_compensated_discrete_gradient_flux_kernel_wp10c9d6c7c3b5c4f25fizzi5 as parent  # noqa:E402
WORK_PACKAGE=parent.AUTHORIZED_NEXT;CLASSIFICATION="bounded_nonlinear_split_microstep_manifest_frozen";AUTHORIZED_NEXT="WP10c9d6c7c3b5c4f25fizzj1_bounded_nonlinear_split_microstep_kernel";PASS_NEXT="definitions_only_WP10c9d6c7c3b5c4f25fizzk_short_restartable_nonlinear_atlas_trajectory_manifest";ARTIFACT="causal_inner_bounded_nonlinear_split_microstep_manifest_wp10c9d6c7c3b5c4f25fizzj";CANONICAL_DIRECTORY=ROOT/"results/canonical"/ARTIFACT;REPORT_RELATIVE="docs/reports/current/CODEX_CAUSAL_INNER_BOUNDED_NONLINEAR_SPLIT_MICROSTEP_MANIFEST_WP10C9D6C7C3B5C4F25FIZZJ_2026-08-26.md";REPORT_PATH=ROOT/REPORT_RELATIVE;THIS_RUNNER="scripts/run_causal_inner_bounded_nonlinear_split_microstep_manifest_wp10c9d6c7c3b5c4f25fizzj.py";THIS_TEST="tests/test_causal_inner_bounded_nonlinear_split_microstep_manifest_wp10c9d6c7c3b5c4f25fizzj.py";PARENT_SHA256="3de755c0beb6d215dd2b73e9e1f2f34828881e50a237ae5c0a010b2e433ec5a1";CANONICAL_MANIFEST=ROOT/"results/manifests/canonical_artifacts.csv";CANONICAL_SUMMARY=ROOT/"results/manifests/canonical_summary.json"
def _u():return parent._u()
def _validate_parent(clean=False):
 u=_u()
 if u._sha256(parent.CANONICAL_DIRECTORY/"SHA256SUMS.txt")!=PARENT_SHA256:raise RuntimeError("compensated flux certificate checksum changed")
 h=u._validate_checksums(parent.CANONICAL_DIRECTORY);s=u._read_json(parent.CANONICAL_DIRECTORY/"summary.json");m=u._read_json(parent.CANONICAL_DIRECTORY/"kernel_metrics.json")
 if not s["passed"] or not s["compensated_discrete_gradient_flux_certified"] or m["passing_endpoint_pair_count"]!=376 or s["authorized_next"]!=WORK_PACKAGE or s["complete_cycle_execution_authorized"]:raise RuntimeError("compensated flux classification changed")
 if clean and u._git("status","--short","--untracked-files=no"):raise RuntimeError("microstep manifest needs clean tracked tree")
 return h
def _contract():return {"schema_version":1,"work_package":WORK_PACKAGE,"classification":CLASSIFICATION,"state":{"equilibrium_core":"four temporal currents U=(J^t,T^tt,T^tR,T^tphi)","entropy":"eta(v)=v dot U(v)-X^t(v), evaluated with compensated alpha and flux arithmetic","shear_height":"five STF and two height-port coordinates advanced by the certified midpoint/Cayley split"},"recovery":{"unknowns":"log rho, log T, and two unconstrained rapidity coordinates","map":"primitive -> compensated entropy point -> temporal currents","solver":"scaled trust-region least squares seeded by the accepted old primitive","residual_gate":1e-11,"accepted_state_only":True},"spatial_step":{"grid":"three-cell periodic frozen-geometry local patch","interface_flux":"certified compensated discrete-gradient radial flux","residual":"conservative flux difference accumulated high and low separately","proposal":"explicit midpoint RK2","entropy_relaxation":"one scalar gamma applied to the full RK increment so total discrete eta equals its prospectively declared target","gamma_interval":[.8,1.2],"coefficient_policy":"reanchor only after an accepted full split step"},"ports":{"composition":"source half, relaxed equilibrium transport full, source half","source_heat":"exact midpoint reservoir-loss deposit","STF_connection":"certified polar isometry"},"kernel":{"selected_witness_indices":[0,10,20,30,40,46],"patches_per_witness":2,"CFL_factors":[.02,.01],"conserved_recovery_gate":1e-11,"conservation_gate":2e-12,"entropy_gate":2e-11,"trust_radius_gate":1.0,"step_halving_order_gate":1.8,"accepted_microsteps_per_case":1,"trajectory_authorized":False},"decision":{"pass_classification":"bounded_nonlinear_split_microstep_kernel_certified","pass_authorized_next":PASS_NEXT,"failure_classification":"bounded_nonlinear_split_microstep_kernel_failed"},"claim_boundary":{"complete_cycle_execution_authorized":False},"authorized_next":AUTHORIZED_NEXT}
def _update(s):
 u=_u();rows=list(csv.DictReader(CANONICAL_MANIFEST.open(newline="",encoding="utf-8")));rows=[r for r in rows if r.get("case")!=ARTIFACT]
 for p in sorted(CANONICAL_DIRECTORY.iterdir()):
  if p.is_file():rows.append({"case":ARTIFACT,"path":str(p.relative_to(ROOT)),"bytes":str(p.stat().st_size),"sha256":u._sha256(p),"scientific_status":"SUPPORTED"})
 with CANONICAL_MANIFEST.open("w",newline="",encoding="utf-8") as h:w=csv.DictWriter(h,fieldnames=("case","path","bytes","sha256","scientific_status"),lineterminator="\n");w.writeheader();w.writerows(rows)
 c=u._read_json(CANONICAL_SUMMARY);c.setdefault("artifacts",{})[ARTIFACT]={"path":str(CANONICAL_DIRECTORY.relative_to(ROOT)),"classification":CLASSIFICATION,"passed":True};c.update({"case_count":len({r['case'] for r in rows}),"file_count":len(rows),"total_bytes":sum(int(r['bytes']) for r in rows),"all_payload_hashes_recorded":True,"latest_source_parent_commit":u._git("rev-parse","HEAD"),"latest_work_package":WORK_PACKAGE});u._write_json(CANONICAL_SUMMARY,c)
def _freeze():
 if CANONICAL_DIRECTORY.exists() or REPORT_PATH.exists():raise RuntimeError("microstep manifest exists")
 h=_validate_parent(True);u=_u();CANONICAL_DIRECTORY.mkdir(parents=True);u._write_json(CANONICAL_DIRECTORY/"microstep_contract.json",_contract());s={"schema_version":1,"work_package":WORK_PACKAGE,"classification":CLASSIFICATION,"passed":True,"definitions_only":True,"compensated_flux_preserved":True,"bounded_nonlinear_microstep_certified":False,"trajectory_authorized":False,"complete_cycle_execution_authorized":False,"authorized_next":AUTHORIZED_NEXT};u._write_json(CANONICAL_DIRECTORY/"summary.json",s);u._write_json(CANONICAL_DIRECTORY/"input_lock.json",{"parent_artifact":parent.ARTIFACT,"parent_checksum_manifest_sha256":PARENT_SHA256,"parent_hashes":h});REPORT_PATH.parent.mkdir(parents=True,exist_ok=True);REPORT_PATH.write_text("# Bounded nonlinear split-microstep manifest\n\nThe physical equilibrium core advances conservatively with the compensated interface flux and an RK2 proposal. A single relaxation scalar restores the nonlinear discrete entropy target. Primitive recovery uses bounded rapidity coordinates, while the seven port variables retain their certified midpoint/Cayley ledgers.\n\nThis package is definitions-only and authorizes one-step proof cases only, not a trajectory or cycle.\n",encoding="utf-8");src=(THIS_RUNNER,THIS_TEST,REPORT_RELATIVE);u._write_json(CANONICAL_DIRECTORY/"provenance.json",{"implementation_commit":u._git("rev-parse","HEAD"),"source_hashes":{p:u._sha256(ROOT/p) for p in src}});names=sorted(p.name for p in CANONICAL_DIRECTORY.iterdir());(CANONICAL_DIRECTORY/"SHA256SUMS.txt").write_text("".join(f"{u._sha256(CANONICAL_DIRECTORY/n)}  {n}\n" for n in names));_update(s);return s
def main():
 p=argparse.ArgumentParser();p.add_argument("--freeze",action="store_true");a=p.parse_args();
 if not a.freeze:p.error("choose --freeze")
 print(json.dumps(_freeze(),indent=2,sort_keys=True));return 0
if __name__=="__main__":raise SystemExit(main())
