#!/usr/bin/env python3
"""Certify the endpoint-only conditioned discrete-gradient entropy flux."""
from __future__ import annotations
import argparse,csv,json,os,platform,sys,time
from dataclasses import asdict
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
for p in (ROOT/"src",ROOT/"scripts"):
    if str(p) not in sys.path:sys.path.insert(0,str(p))
sys.setrecursionlimit(max(sys.getrecursionlimit(),5000))
import run_causal_inner_conditioned_discrete_gradient_flux_manifest_wp10c9d6c7c3b5c4f25fizzi2 as manifest  # noqa:E402
import run_causal_inner_local_nonlinear_atlas_trust_region_kernel_wp10c9d6c7c3b5c4f25fizzi1 as rejected  # noqa:E402
from imri_qpe.layer3_minidisk_1d.causal_inner_nonlinear_port_atlas import audit_conditioned_discrete_gradient_radial_flux,equilibrium_entropy_point_from_primitive  # noqa:E402
WORK_PACKAGE=manifest.AUTHORIZED_NEXT;PASS_CLASSIFICATION="conditioned_discrete_gradient_flux_kernel_certified";FAIL_CLASSIFICATION="conditioned_discrete_gradient_flux_kernel_failed";AUTHORIZED_NEXT=manifest.PASS_NEXT;ARTIFACT="causal_inner_conditioned_discrete_gradient_flux_kernel_wp10c9d6c7c3b5c4f25fizzi3";CANONICAL_DIRECTORY=ROOT/"results/canonical"/ARTIFACT;REPORT_RELATIVE="docs/reports/current/CODEX_CAUSAL_INNER_CONDITIONED_DISCRETE_GRADIENT_FLUX_KERNEL_WP10C9D6C7C3B5C4F25FIZZI3_2026-08-26.md";REPORT_PATH=ROOT/REPORT_RELATIVE;THIS_RUNNER="scripts/run_causal_inner_conditioned_discrete_gradient_flux_kernel_wp10c9d6c7c3b5c4f25fizzi3.py";THIS_TEST="tests/test_causal_inner_conditioned_discrete_gradient_flux_kernel_wp10c9d6c7c3b5c4f25fizzi3.py";PHYSICAL_SOURCE="src/imri_qpe/layer3_minidisk_1d/causal_inner_nonlinear_port_atlas.py";PHYSICAL_TEST="tests/test_causal_inner_nonlinear_port_atlas.py";PARENT_SHA256="d2dd1d84aeb03ea6425446a27cfee62a7c8a0eeaa97bdae7f48109433d41a10c";CANONICAL_MANIFEST=ROOT/"results/manifests/canonical_artifacts.csv";CANONICAL_SUMMARY=ROOT/"results/manifests/canonical_summary.json"
def _u():return manifest._u()
def _validate_parent(clean=False):
 u=_u()
 if u._sha256(manifest.CANONICAL_DIRECTORY/"SHA256SUMS.txt")!=PARENT_SHA256:raise RuntimeError("discrete-gradient manifest checksum changed")
 h=u._validate_checksums(manifest.CANONICAL_DIRECTORY);s=u._read_json(manifest.CANONICAL_DIRECTORY/"summary.json");c=u._read_json(manifest.CANONICAL_DIRECTORY/"discrete_gradient_contract.json")
 if not s["passed"] or not s["definitions_only"] or not s["straight_entropy_path_rejection_preserved"] or s["authorized_next"]!=WORK_PACKAGE or c["kernel"]["trajectory_steps"]:raise RuntimeError("discrete-gradient contract changed")
 if clean and u._git("status","--short","--untracked-files=no"):raise RuntimeError("discrete-gradient kernel needs clean tracked tree")
 return h,c
def _certificate():
 began=time.perf_counter();_,c=_validate_parent();wb=time.perf_counter();physical=list(rejected.witnesses._physical_witnesses());ws=time.perf_counter()-wb;rows=[];tad=[];swap=[];cons=[];corr=[];pen=[];charts=[];radii=[]
 for index,label,radius,old,chart in physical:
  H=float(np.exp(chart[5]));rho=float(np.exp(chart[0]))/(2*H);T=float(np.exp(chart[3]));ur=float(chart[1]);uphi=float(chart[2]);charts.append(chart);radii.append(radius)
  for di,direction in enumerate(rejected._DIRECTIONS):
   drho,dtemp,dur,duphi,_=direction*np.asarray((.01,.01,.002,.002,.005));left=equilibrium_entropy_point_from_primitive(old.geometry,density=rho*np.exp(-.5*drho),temperature=T*np.exp(-.5*dtemp),proper_half_thickness=H,radial_velocity_over_c=ur-.5*dur,azimuthal_velocity_over_c=uphi-.5*duphi);right=equilibrium_entropy_point_from_primitive(old.geometry,density=rho*np.exp(.5*drho),temperature=T*np.exp(.5*dtemp),proper_half_thickness=H,radial_velocity_over_c=ur+.5*dur,azimuthal_velocity_over_c=uphi+.5*duphi);a=audit_conditioned_discrete_gradient_radial_flux(left,right);rows.append({"witness_index":index,"witness_label":label,"direction_index":di,"radius_cm":radius,"audit":asdict(a),"passed":a.passed});tad.append(a.tadmor_relative_defect);swap.append(a.swap_symmetry_relative_defect);cons.append(a.endpoint_consistency_relative_defect);corr.append(a.weighted_correction_relative_norm);pen.append(a.entropy_penalty_positive_part)
 passed=bool(len(rows)==376 and all(r["passed"] for r in rows));m={"schema_version":1,"work_package":WORK_PACKAGE,"classification":PASS_CLASSIFICATION if passed else FAIL_CLASSIFICATION,"passed":passed,"endpoint_pair_count":len(rows),"passing_endpoint_pair_count":sum(r["passed"] for r in rows),"maximum_tadmor_relative_defect":float(max(tad)),"maximum_swap_symmetry_relative_defect":float(max(swap)),"maximum_endpoint_consistency_relative_defect":float(max(cons)),"maximum_weighted_correction_relative_norm":float(max(corr)),"maximum_entropy_penalty_positive_part":float(max(pen)),"straight_entropy_path_rejection_preserved":True,"STF_connection_and_endpoint_atlas_support_preserved":True,"trajectory_steps":0,"complete_cycle_execution_authorized":False,"witness_construction_wall_seconds":ws,"certificate_wall_seconds":time.perf_counter()-began,"rows":rows,"authorized_next":AUTHORIZED_NEXT if passed else None};a={"witness_charts7":np.asarray(charts),"witness_radii_cm":np.asarray(radii),"tadmor_relative_defects":np.asarray(tad),"swap_symmetry_relative_defects":np.asarray(swap),"endpoint_consistency_relative_defects":np.asarray(cons),"weighted_correction_relative_norms":np.asarray(corr),"entropy_penalty_positive_parts":np.asarray(pen)};del c;return m,a
def _update(s):
 u=_u();rows=list(csv.DictReader(CANONICAL_MANIFEST.open(newline="",encoding="utf-8")));rows=[r for r in rows if r.get("case")!=ARTIFACT];status="SUPPORTED" if s["passed"] else "REJECTED"
 for p in sorted(CANONICAL_DIRECTORY.iterdir()):
  if p.is_file():rows.append({"case":ARTIFACT,"path":str(p.relative_to(ROOT)),"bytes":str(p.stat().st_size),"sha256":u._sha256(p),"scientific_status":status})
 with CANONICAL_MANIFEST.open("w",newline="",encoding="utf-8") as h:w=csv.DictWriter(h,fieldnames=("case","path","bytes","sha256","scientific_status"),lineterminator="\n");w.writeheader();w.writerows(rows)
 c=u._read_json(CANONICAL_SUMMARY);c.setdefault("artifacts",{})[ARTIFACT]={"path":str(CANONICAL_DIRECTORY.relative_to(ROOT)),"classification":s["classification"],"passed":s["passed"]};c.update({"case_count":len({r['case'] for r in rows}),"file_count":len(rows),"total_bytes":sum(int(r['bytes']) for r in rows),"all_payload_hashes_recorded":True,"latest_source_parent_commit":u._git("rev-parse","HEAD"),"latest_work_package":WORK_PACKAGE});u._write_json(CANONICAL_SUMMARY,c)
def _canon(m,a):
 if CANONICAL_DIRECTORY.exists() or REPORT_PATH.exists():raise RuntimeError("discrete-gradient certificate exists")
 h,_=_validate_parent(True);u=_u();CANONICAL_DIRECTORY.mkdir(parents=True);u._write_json(CANONICAL_DIRECTORY/"kernel_metrics.json",m);np.savez_compressed(CANONICAL_DIRECTORY/"kernel_arrays.npz",**a);s={"schema_version":1,"work_package":WORK_PACKAGE,"classification":m["classification"],"passed":m["passed"],"straight_entropy_path_rejection_preserved":True,"conditioned_discrete_gradient_flux_certified":m["passed"],"bounded_nonlinear_microstep_authorized":False,"trajectory_authorized":False,"complete_cycle_execution_authorized":False,"authorized_next":m["authorized_next"]};u._write_json(CANONICAL_DIRECTORY/"summary.json",s);u._write_json(CANONICAL_DIRECTORY/"input_lock.json",{"manifest_artifact":manifest.ARTIFACT,"manifest_checksum_manifest_sha256":PARENT_SHA256,"manifest_hashes":h});REPORT_PATH.parent.mkdir(parents=True,exist_ok=True);REPORT_PATH.write_text(f"# Conditioned discrete-gradient flux certificate\n\nClassification: `{m['classification']}`.\n\n{m['passing_endpoint_pair_count']}/{m['endpoint_pair_count']} endpoint pairs pass. Worst Tadmor defect: `{m['maximum_tadmor_relative_defect']:.6e}`; weighted correction: `{m['maximum_weighted_correction_relative_norm']:.6e}`. The rejected straight path remains rejected.\n\nNo trajectory was executed. Authorized next: `{m['authorized_next']}`.\n",encoding="utf-8");src=(THIS_RUNNER,THIS_TEST,PHYSICAL_SOURCE,PHYSICAL_TEST,REPORT_RELATIVE);u._write_json(CANONICAL_DIRECTORY/"provenance.json",{"implementation_commit":u._git("rev-parse","HEAD"),"source_hashes":{p:u._sha256(ROOT/p) for p in src},"python":sys.version,"numpy":np.__version__,"platform":platform.platform(),"thread_environment":{n:os.environ.get(n,"") for n in ("OPENBLAS_NUM_THREADS","OMP_NUM_THREADS","VECLIB_MAXIMUM_THREADS")}});names=sorted(p.name for p in CANONICAL_DIRECTORY.iterdir());(CANONICAL_DIRECTORY/"SHA256SUMS.txt").write_text("".join(f"{u._sha256(CANONICAL_DIRECTORY/n)}  {n}\n" for n in names));_update(s);return s
def main():
 p=argparse.ArgumentParser();p.add_argument("--run",action="store_true");x=p.parse_args();
 if not x.run:p.error("choose --run")
 m,a=_certificate();print(json.dumps(m,indent=2,sort_keys=True),flush=True);return 0 if _canon(m,a)["passed"] else 2
if __name__=="__main__":raise SystemExit(main())
