"""Diagnostic scan of softened vertical-Eddington wind thresholds."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import numpy as np

from imri_qpe.layer3_minidisk_1d.winds import wind_energy_per_mass
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot
from run_standard_slim_analytic_seed_audit import fmt, json_safe
from run_standard_slim_stream_anchor_regression import params_from_checkpoint
from run_standard_slim_stream_wind_trigger_audit import ROOT, configured_anchors, interval_profile, trapz_interval


TABLE_OUTPUT = ROOT / os.environ.get(
    "IMBH_STANDARD_SLIM_STREAM_SOFT_WIND_TABLE",
    "outputs/tables/high_mdot_stream_m5_soft_wind_threshold_scan.md",
)
JSON_OUTPUT = TABLE_OUTPUT.with_suffix(".json")
FIGURE_OUTPUT = ROOT / os.environ.get(
    "IMBH_STANDARD_SLIM_STREAM_SOFT_WIND_FIGURE",
    "outputs/figures/high_mdot_stream_m5_soft_wind_threshold_scan.png",
)


def configured_chi_values() -> tuple[float, ...]:
    raw = os.environ.get("IMBH_STANDARD_SLIM_STREAM_SOFT_WIND_CHI", "1.0,0.999,0.995,0.99,0.98")
    values: list[float] = []
    for piece in raw.split(","):
        text = piece.strip()
        if not text:
            continue
        value = float(text)
        if not 0.0 < value <= 1.0:
            raise ValueError("soft wind chi values must lie in (0, 1]")
        values.append(value)
    if not values:
        raise ValueError("at least one soft wind chi value is required")
    return tuple(values)


def implied_mass_loss_fraction(qwind: np.ndarray, profile: dict[str, np.ndarray], params) -> float:
    R_cm = profile["R_rg"] * params.r_g
    E_w = wind_energy_per_mass(params.M2_g, R_cm)
    dot_sigma_w = qwind / (np.asarray(E_w, dtype=float) + 1.0e-300)
    return float(trapz_interval(dot_sigma_w, profile["R_rg"], params) / params.Mdot_g_s)


def first_last_active_radius(active: np.ndarray, R_rg: np.ndarray) -> tuple[float, float]:
    if not np.any(active):
        return np.nan, np.nan
    active_R = R_rg[active]
    return float(np.min(active_R)), float(np.max(active_R))


def row_for_chi(label: str, path: Path, params, profile: dict[str, np.ndarray], chi_edd: float) -> dict[str, Any]:
    qwind = np.maximum(profile["Q_avail"] - chi_edd * profile["Q_edd_z"], 0.0)
    active = qwind > 0.0
    qv = profile["Q_visc"]
    qr = profile["Q_rad"]
    qa = profile["Q_adv"]
    qedd = profile["Q_edd_z"]
    int_wind = trapz_interval(qwind, profile["R_rg"], params)
    int_visc_abs = trapz_interval(np.abs(qv), profile["R_rg"], params) + 1.0e-300
    int_rad_abs = trapz_interval(np.abs(qr), profile["R_rg"], params) + 1.0e-300
    int_adv_abs = trapz_interval(np.abs(qa), profile["R_rg"], params) + 1.0e-300
    int_edd = trapz_interval(qedd, profile["R_rg"], params) + 1.0e-300
    peak_idx = int(np.argmax(qwind)) if qwind.size else 0
    active_min_R, active_max_R = first_last_active_radius(active, profile["R_rg"])
    return {
        "label": label,
        "path": str(path.relative_to(ROOT)),
        "ratio": float(params.mdot_edd_ratio),
        "R_out_rg": float(params.R_out_rg),
        "N": int(params.n_nodes),
        "source_fraction": float(params.stream_source_fraction),
        "heat_eta": float(params.stream_heating_efficiency),
        "chi_edd": float(chi_edd),
        "max_Qavail_over_Qedd": float(np.max(profile["Qavail_over_Qedd"])),
        "active_interval_fraction": float(np.count_nonzero(active) / max(active.size, 1)),
        "active_min_R_rg": active_min_R,
        "active_max_R_rg": active_max_R,
        "peak_Qwind_R_rg": float(profile["R_rg"][peak_idx]) if qwind[peak_idx] > 0.0 else np.nan,
        "max_Qwind_Qvisc": float(np.max(qwind / (np.abs(qv) + 1.0e-300))),
        "integrated_Qwind_Qvisc": float(int_wind / int_visc_abs),
        "integrated_Qwind_Qrad": float(int_wind / int_rad_abs),
        "integrated_Qwind_Qadv_abs": float(int_wind / int_adv_abs),
        "integrated_Qwind_Qedd": float(int_wind / int_edd),
        "implied_Mwind_Mdot_inner": implied_mass_loss_fraction(qwind, profile, params),
    }


def scan_anchor(label: str, path: Path, z: np.ndarray, params, chi_values: tuple[float, ...]) -> tuple[list[dict[str, Any]], dict[str, np.ndarray]]:
    profile = interval_profile(z, params)
    rows = [row_for_chi(label, path, params, profile, chi) for chi in chi_values]
    return rows, profile


def write_table(rows: list[dict[str, Any]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Standard Slim Stream Soft Wind-Threshold Scan",
        "",
        "Generated by `scripts/run_standard_slim_stream_soft_wind_threshold_scan.py`.",
        "",
        "Diagnostic only: the BVP solution is not changed. The scan evaluates",
        "",
        "```text",
        "Qwind_raw = max(Qavail - chi_edd Q_Edd,z, 0)",
        "dotSigma_w = Qwind_raw / (GM / 2R)",
        "```",
        "",
        "| anchor | eta_heat | chi_edd | max Qavail/Qedd | active frac | active R range/rg | peak R/rg | int Qwind/Qvisc | int Qwind/Qedd | implied Mwind/Min |",
        "|---|---:|---:|---:|---:|---|---:|---:|---:|---:|",
    ]
    for row in rows:
        display = {
            key: fmt(value) if isinstance(value, (float, int, np.floating, np.integer)) else value
            for key, value in row.items()
        }
        if np.isfinite(row["active_min_R_rg"]):
            R_range = f"{fmt(row['active_min_R_rg'])}-{fmt(row['active_max_R_rg'])}"
        else:
            R_range = "inactive"
        lines.append(
            "| {label} | {heat_eta} | {chi_edd} | {max_Qavail_over_Qedd} | {active_interval_fraction} | "
            f"{R_range} | "
            "{peak_Qwind_R_rg} | {integrated_Qwind_Qvisc} | {integrated_Qwind_Qedd} | "
            "{implied_Mwind_Mdot_inner} |".format(**display)
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")
    JSON_OUTPUT.write_text(json.dumps(json_safe(rows), indent=2, sort_keys=True) + "\n")


def _polyline(points: list[tuple[float, float]]) -> list[tuple[int, int]]:
    return [(int(round(x)), int(round(y))) for x, y in points]


def write_figure(
    profiles: dict[str, dict[str, np.ndarray]],
    rows: list[dict[str, Any]],
    chi_values: tuple[float, ...],
) -> None:
    try:
        from PIL import Image, ImageDraw, ImageFont
    except Exception as exc:
        print(f"skipping figure: PIL unavailable ({exc})", flush=True)
        return
    if not profiles:
        return
    FIGURE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    width, height = 1200, 780
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default()
    colors = [(31, 119, 180), (214, 39, 40), (44, 160, 44), (148, 103, 189)]

    top = (95, 80, 1115, 430)
    bottom = (95, 510, 1115, 710)
    draw.rectangle(top, outline=(70, 70, 70), width=2)
    draw.rectangle(bottom, outline=(70, 70, 70), width=2)

    all_R = np.concatenate([profile["R_rg"] for profile in profiles.values()])
    xmin, xmax = float(np.log10(np.min(all_R))), float(np.log10(np.max(all_R)))
    ymin = min(0.975, min(chi_values) - 0.002)
    ymax = 1.0005
    x0, y0, x1, y1 = top

    def map_x(R_rg: np.ndarray) -> np.ndarray:
        return x0 + (np.log10(R_rg) - xmin) / (xmax - xmin) * (x1 - x0)

    def map_y(values: np.ndarray) -> np.ndarray:
        clipped = np.clip(np.asarray(values, dtype=float), ymin, ymax)
        return y1 - (clipped - ymin) / (ymax - ymin) * (y1 - y0)

    for tick in range(int(np.ceil(xmin)), int(np.floor(xmax)) + 1):
        x = x0 + (tick - xmin) / (xmax - xmin) * (x1 - x0)
        draw.line((x, y0, x, y1), fill=(235, 235, 235))
        draw.text((x - 12, y1 + 8), f"1e{tick}", fill=(40, 40, 40), font=font)
    for value in sorted(set((*chi_values, 1.0))):
        y = float(map_y(np.asarray([value]))[0])
        if y0 <= y <= y1:
            shade = (0, 0, 0) if np.isclose(value, 1.0) else (165, 165, 165)
            draw.line((x0, y, x1, y), fill=shade, width=2 if np.isclose(value, 1.0) else 1)
            draw.text((x1 - 75, y - 8), f"{value:g}", fill=shade, font=font)
    for value in (0.98, 0.99, 0.995, 1.0):
        if ymin <= value <= ymax:
            y = float(map_y(np.asarray([value]))[0])
            draw.text((35, y - 5), f"{value:g}", fill=(40, 40, 40), font=font)

    for idx, (label, profile) in enumerate(profiles.items()):
        color = colors[idx % len(colors)]
        points = list(zip(map_x(profile["R_rg"]), map_y(profile["Qavail_over_Qedd"])))
        if len(points) > 1:
            draw.line(_polyline(points), fill=color, width=3)
        draw.rectangle((x0 + 15, y0 + 18 + 22 * idx, x0 + 30, y0 + 30 + 22 * idx), fill=color)
        draw.text((x0 + 38, y0 + 16 + 22 * idx), label, fill=(30, 30, 30), font=font)

    draw.text((x0, 30), "Soft wind-trigger diagnostic: Qavail/QEdd,z", fill=(20, 20, 20), font=font)
    draw.text((505, 455), "R / rg", fill=(20, 20, 20), font=font)
    draw.text((18, 50), "Qavail/QEdd,z", fill=(20, 20, 20), font=font)

    bx0, by0, bx1, by1 = bottom
    by_min, by_max = 0.0, max(1.0e-12, max(row["implied_Mwind_Mdot_inner"] for row in rows) * 1.08)
    chi_min, chi_max = min(chi_values), max(chi_values)
    chi_span = max(chi_max - chi_min, 1.0e-12)

    def map_chi(chi: float) -> float:
        return bx0 + (chi - chi_min) / chi_span * (bx1 - bx0)

    def map_mass(value: float) -> float:
        return by1 - (value - by_min) / (by_max - by_min + 1.0e-300) * (by1 - by0)

    for chi in chi_values:
        x = map_chi(chi)
        draw.line((x, by0, x, by1), fill=(235, 235, 235))
        draw.text((x - 18, by1 + 8), f"{chi:g}", fill=(40, 40, 40), font=font)
    for frac in np.linspace(0.0, 1.0, 5):
        value = by_min + frac * (by_max - by_min)
        y = map_mass(value)
        draw.line((bx0, y, bx1, y), fill=(235, 235, 235))
        draw.text((25, y - 5), f"{value:.2e}", fill=(40, 40, 40), font=font)

    for idx, label in enumerate(profiles):
        color = colors[idx % len(colors)]
        label_rows = [row for row in rows if row["label"] == label]
        label_rows.sort(key=lambda item: item["chi_edd"])
        points = [(map_chi(row["chi_edd"]), map_mass(row["implied_Mwind_Mdot_inner"])) for row in label_rows]
        if len(points) > 1:
            draw.line(_polyline(points), fill=color, width=3)
        for x, y in points:
            draw.ellipse((x - 4, y - 4, x + 4, y + 4), fill=color)
    draw.text((bx0, 475), "Implied mass loss for epsilon_w=1 diagnostic", fill=(20, 20, 20), font=font)
    draw.text((505, height - 40), "chi_edd", fill=(20, 20, 20), font=font)
    draw.text((18, 488), "Mwind / Min", fill=(20, 20, 20), font=font)
    image.save(FIGURE_OUTPUT)


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    chi_values = configured_chi_values()
    rows: list[dict[str, Any]] = []
    profiles: dict[str, dict[str, np.ndarray]] = {}
    for label, path in configured_anchors():
        z, params = params_from_checkpoint(path, fiducial, mdot_edd)
        anchor_rows, profile = scan_anchor(label, path, z, params, chi_values)
        rows.extend(anchor_rows)
        profiles[label] = profile
        best = max(anchor_rows, key=lambda row: row["implied_Mwind_Mdot_inner"])
        print(
            f"{label}: max_Qavail/Qedd={best['max_Qavail_over_Qedd']:.6f} "
            f"max_implied_Mwind/Min={best['implied_Mwind_Mdot_inner']:.3e} "
            f"at chi={best['chi_edd']:.5g}",
            flush=True,
        )
    write_table(rows)
    write_figure(profiles, rows, chi_values)
    print(f"wrote {TABLE_OUTPUT}", flush=True)
    print(f"wrote {FIGURE_OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
