"""Adaptive high-rate continuation audit for the transonic homotopy branch."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    remap_profile_to_new_sonic_grid,
    solve_low_mdot_transonic_homotopy,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_high_rate_ladder.md"
RESIDUAL_TOL = 3.0e-4
R_OUT_RG = 3000.0
SCOUT_N = 48
CONFIRM_N = 64
WARMUP_RATIOS = (1.0e-3, 2.5e-3, 5.0e-3, 1.0e-2, 2.0e-2, 3.0e-2)
SCOUT_RATIOS = (5.0e-2, 0.1, 0.15, 0.2, 0.3, 0.5, 0.7, 1.0, 1.5, 2.0)
CONFIRM_RATIOS = (0.3, 0.5, 1.0, 1.5, 2.0)
MIN_DLOG_RETRY = 0.035
WARMUP_SONIC_WEIGHTS = (1.0,)
TARGET_SONIC_WEIGHTS = (0.3, 1.0, 3.0)


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def dominant_block(audit) -> str:
    values = {
        "interval_R": abs(audit.interval_radial_max),
        "interval_E": abs(audit.interval_energy_max),
        "outer_Omega": abs(audit.outer_omega),
        "outer_E": abs(audit.outer_energy),
        "D": abs(audit.sonic_D),
        "C1": abs(audit.sonic_C1),
        "C2": abs(audit.sonic_C2),
    }
    return max(values, key=values.get)


def accepted_for_continuation(final) -> bool:
    status = final.status
    return bool(
        np.isfinite(final.max_residual)
        and final.max_residual <= RESIDUAL_TOL
        and status.optimizer_acceptable
        and status.equations_converged
        and status.sonic_regular
        and status.active_bounds_clear
        and status.positive_state
        and status.outer_thin
    )


def solve_one(
    *,
    M2_g: float,
    mdot_edd: float,
    alpha: float,
    ratio: float,
    n_nodes: int,
    R_out_rg: float,
    seed_profile,
    sonic_weight_sequence: tuple[float, ...],
):
    params = TransonicSlimParams(
        M2_g=M2_g,
        Mdot_g_s=ratio * mdot_edd,
        alpha=alpha,
        n_nodes=n_nodes,
        R_out_rg=R_out_rg,
        max_nfev=1800,
        residual_tol=RESIDUAL_TOL,
    )
    guess = remap_profile_to_new_sonic_grid(seed_profile, params) if seed_profile is not None else None
    result = solve_low_mdot_transonic_homotopy(
        params,
        initial_guess=guess,
        max_nfev_per_stage=900,
        final_max_nfev=1800,
        sonic_weight_sequence=sonic_weight_sequence,
    )
    return params, result


def row_from_result(label: str, ratio: float, n_nodes: int, R_out_rg: float, params, result, seed_label: str) -> dict[str, object]:
    final = result.final_result
    profile = final.profile
    audit = final.residual_audit
    status = final.status
    b2_stages = [stage for stage in result.stages if stage.name.startswith("B2_")]
    max_qadv_qvisc = float(np.max(np.abs(profile.Q_adv) / (np.abs(profile.Q_visc) + 1.0e-300)))
    max_xi = float(np.max(profile.xi_eff))
    accepted = accepted_for_continuation(final)
    return {
        "label": label,
        "seed_label": seed_label,
        "ratio": ratio,
        "n_nodes": n_nodes,
        "R_out_rg": R_out_rg,
        "accepted": accepted,
        "physical": status.physically_valid,
        "optimizer_ok": status.optimizer_acceptable,
        "equations": status.equations_converged,
        "sonic": status.sonic_regular,
        "outer_thin": status.outer_thin,
        "dominant": dominant_block(audit),
        "lambda_ratio": audit.lambda0_over_lK_isco,
        "Rson_rg": profile.sonic_radius / params.r_g,
        "max_HR": float(np.max(profile.H_over_R)),
        "outer_HR": audit.outer_H_over_R,
        "outer_Qadv_over_Qvisc": audit.outer_Qadv_over_Qvisc,
        "max_Qadv_over_Qvisc": max_qadv_qvisc,
        "integrated_advective_fraction": profile.integrated_advective_fraction,
        "max_xi": max_xi,
        "max_residual": final.max_residual,
        "interval_radial": audit.interval_radial_max,
        "interval_energy": audit.interval_energy_max,
        "outer_omega": audit.outer_omega,
        "outer_energy": audit.outer_energy,
        "sonic_D": audit.sonic_D,
        "sonic_C1": audit.sonic_C1,
        "sonic_C2": audit.sonic_C2,
        "stage_B2_last": b2_stages[-1].max_residual if b2_stages else np.nan,
        "nfev": final.nfev,
        "message": final.message,
    }


def write_table(rows: list[dict[str, object]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Transonic High-Rate Ladder",
        "",
        "Generated by `scripts/run_transonic_high_rate_ladder.py`.",
        "",
        f"Scout baseline: `R_out={R_OUT_RG:g} r_g`, `N={SCOUT_N}`. Confirmations use `N={CONFIRM_N}` at accepted scout milestones.",
        "",
        "| label | seed | N | R_out/r_g | Mdot/Mdot_Edd | accepted | physical | opt ok | equations | sonic | outer thin | dominant | lambda/lK_ISCO | R_son/r_g | max H/R | outer H/R | outer Qadv/Qvisc | max Qadv/Qvisc | int adv frac | max xi | max residual | interval R | interval E | outer Omega | outer E | D | C1 | C2 | B2 max | nfev | message |",
        "|---|---|---:|---:|---:|:---:|:---:|:---:|:---:|:---:|:---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {label} | {seed_label} | {n_nodes} | {R_out_rg} | {ratio} | {accepted} | "
            "{physical} | {optimizer_ok} | {equations} | {sonic} | {outer_thin} | {dominant} | "
            "{lambda_ratio} | {Rson_rg} | {max_HR} | {outer_HR} | {outer_Qadv_over_Qvisc} | "
            "{max_Qadv_over_Qvisc} | {integrated_advective_fraction} | {max_xi} | {max_residual} | "
            "{interval_radial} | {interval_energy} | {outer_omega} | {outer_energy} | {sonic_D} | "
            "{sonic_C1} | {sonic_C2} | {stage_B2_last} | {nfev} | {message} |".format(
                label=row["label"],
                seed_label=row["seed_label"],
                n_nodes=row["n_nodes"],
                R_out_rg=fmt(float(row["R_out_rg"])),
                ratio=fmt(float(row["ratio"])),
                accepted="yes" if row["accepted"] else "no",
                physical="yes" if row["physical"] else "no",
                optimizer_ok="yes" if row["optimizer_ok"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                outer_thin="yes" if row["outer_thin"] else "no",
                dominant=row["dominant"],
                lambda_ratio=fmt(float(row["lambda_ratio"])),
                Rson_rg=fmt(float(row["Rson_rg"])),
                max_HR=fmt(float(row["max_HR"])),
                outer_HR=fmt(float(row["outer_HR"])),
                outer_Qadv_over_Qvisc=fmt(float(row["outer_Qadv_over_Qvisc"])),
                max_Qadv_over_Qvisc=fmt(float(row["max_Qadv_over_Qvisc"])),
                integrated_advective_fraction=fmt(float(row["integrated_advective_fraction"])),
                max_xi=fmt(float(row["max_xi"])),
                max_residual=fmt(float(row["max_residual"])),
                interval_radial=fmt(float(row["interval_radial"])),
                interval_energy=fmt(float(row["interval_energy"])),
                outer_omega=fmt(float(row["outer_omega"])),
                outer_energy=fmt(float(row["outer_energy"])),
                sonic_D=fmt(float(row["sonic_D"])),
                sonic_C1=fmt(float(row["sonic_C1"])),
                sonic_C2=fmt(float(row["sonic_C2"])),
                stage_B2_last=fmt(float(row["stage_B2_last"])),
                nfev=row["nfev"],
                message=str(row["message"]).replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")


def append_and_report(rows: list[dict[str, object]], row: dict[str, object]) -> None:
    rows.append(row)
    write_table(rows)
    print(
        f"{row['label']} N={row['n_nodes']} rate={row['ratio']:.4g} "
        f"accepted={row['accepted']} max={row['max_residual']:.4g} "
        f"H/R={row['max_HR']:.4g} adv={row['integrated_advective_fraction']:.4g} "
        f"dom={row['dominant']}",
        flush=True,
    )


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    rows: list[dict[str, object]] = []

    warmup_profile = None
    for ratio in WARMUP_RATIOS:
        params, result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=24,
            R_out_rg=1000.0,
            seed_profile=warmup_profile,
            sonic_weight_sequence=WARMUP_SONIC_WEIGHTS,
        )
        row = row_from_result("warmup", ratio, 24, 1000.0, params, result, "previous")
        append_and_report(rows, row)
        if row["accepted"] or (result.final_result.status.sonic_regular and result.final_result.max_residual < 8.0e-4):
            warmup_profile = result.final_result.profile

    accepted_profiles: dict[float, object] = {}
    scout_profile = warmup_profile
    accepted_ratio: float | None = None
    pending = list(SCOUT_RATIOS)
    while pending:
        ratio = float(pending.pop(0))
        params, result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=SCOUT_N,
            R_out_rg=R_OUT_RG,
            seed_profile=scout_profile,
            sonic_weight_sequence=TARGET_SONIC_WEIGHTS,
        )
        row = row_from_result("scout", ratio, SCOUT_N, R_OUT_RG, params, result, "accepted")
        append_and_report(rows, row)
        if row["accepted"]:
            scout_profile = result.final_result.profile
            accepted_profiles[ratio] = scout_profile
            accepted_ratio = ratio
            continue
        if accepted_ratio is None:
            break
        dlog = np.log(ratio / accepted_ratio)
        if dlog <= MIN_DLOG_RETRY:
            break
        midpoint = float(np.exp(0.5 * (np.log(ratio) + np.log(accepted_ratio))))
        if not pending or abs(pending[0] - midpoint) / midpoint > 1.0e-8:
            pending.insert(0, ratio)
            pending.insert(0, midpoint)

    confirm_profile = None
    for ratio in CONFIRM_RATIOS:
        if ratio not in accepted_profiles:
            continue
        params, result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=CONFIRM_N,
            R_out_rg=R_OUT_RG,
            seed_profile=confirm_profile if confirm_profile is not None else accepted_profiles[ratio],
            sonic_weight_sequence=TARGET_SONIC_WEIGHTS,
        )
        row = row_from_result("confirm", ratio, CONFIRM_N, R_OUT_RG, params, result, "N48" if confirm_profile is None else "previous_N64")
        append_and_report(rows, row)
        if row["accepted"]:
            confirm_profile = result.final_result.profile

    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
