"""Independent short-join free-tail scans before the exact-branch barrier."""

from __future__ import annotations

import os

# Configure the imported graded-flowmap module before it reads environment
# constants. These match the best transition-shell N96 run.
os.environ.setdefault("IMBH_GRADED_FLOWMAP_EPSILON0", "1e-6")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_MICRO_FIRST_DX", "0.0001")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_MICRO_GROWTH", "1.2")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_MICRO_EXTENT", "0.004")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_TRANSITION_FIRST_DX", "0.001")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_TRANSITION_GROWTH", "1.2")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_MICRO_SOLVE_FORM", "integrated_dx")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_FLOW_WEIGHT", "1000")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_MICRO_WEIGHT", "50")
os.environ.setdefault("IMBH_GRADED_FLOWMAP_TRANSITION_WEIGHT", "10")

from dataclasses import replace
from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d.transonic_local import sonic_derivative_branches
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot

from run_transonic_outer_slope_calibration_audit import fmt
from run_transonic_sonic_reverse_fit import SOURCE_CHECKPOINT, load_context, solve_fit
from run_transonic_two_domain_dynamic_sonic_patch import load_row
from run_transonic_two_domain_sonic_flowmap import LHOPITAL_EPS

from run_transonic_reverse_seed_graded_flowmap_bvp import (
    ACCEPTANCE_LIMIT,
    BRANCH_HALF_WIDTH,
    BRANCH_POINTS,
    GridConfig,
    audit,
    default_grid_config,
    make_params,
    seed_profile,
    solve_graded,
)


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / os.environ.get(
    "IMBH_SHORT_JOIN_TABLE",
    "outputs/tables/transonic_short_join_free_tail_scan.md",
)
R_JOIN_RG = tuple(
    float(piece)
    for piece in os.environ.get("IMBH_SHORT_JOIN_RJOIN_RG", "6.0,6.05,6.1,6.15,6.2")
    .replace(":", ",")
    .split(",")
    if piece.strip()
)
EPSILON_BUF = float(os.environ.get("IMBH_SHORT_JOIN_EPS_BUF", "0.002"))
BRANCH_INDEX = int(os.environ.get("IMBH_SHORT_JOIN_BRANCH", "1"))
N_REGULAR = int(os.environ.get("IMBH_SHORT_JOIN_N_REGULAR", "96"))
MAX_NFEV_RELEASE = int(os.environ.get("IMBH_SHORT_JOIN_MAX_NFEV_RELEASE", "120"))
MAX_NFEV_POLISH = int(os.environ.get("IMBH_SHORT_JOIN_MAX_NFEV_POLISH", "40"))
SEED_MODE = os.environ.get("IMBH_SHORT_JOIN_SEED_MODE", "transition_ode_blend")


def transition_extent_for(logR_son: float, params, R_join_rg: float) -> float:
    return float(np.log(R_join_rg * params.r_g) - logR_son)


def row_for_table(row: dict[str, object], R_join_rg: float, transition_extent: float) -> dict[str, object]:
    out = dict(row)
    out["R_join_rg"] = R_join_rg
    out["transition_extent_requested"] = transition_extent
    out.pop("x", None)
    return out


def write_table(rows: list[dict[str, object]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Short-Join Free-Tail Scan",
        "",
        "Generated by `scripts/run_transonic_short_join_free_tail_scan.py`.",
        "",
        f"Config: `N={N_REGULAR}`, `eps_buf={EPSILON_BUF:g}`, `branch={BRANCH_INDEX}`, "
        f"`release_nfev={MAX_NFEV_RELEASE}`, `polish_nfev={MAX_NFEV_POLISH}`, "
        f"`acceptance={ACCEPTANCE_LIMIT:g}`.",
        "",
        "| R_join/rg | extent | stage | physical | near sonic | selected | dominant | flow | micro R | micro E | trans R | trans E | tail R | tail E | worst R/rg | first tail dx | Rson/rg | lambda0 | int adv | max H/R | a | g_u | g_T | nfev | success | message |",
        "|---:|---:|---|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {R_join_rg} | {transition_extent_requested} | {stage} | {physical_active} | "
            "{near_sonic_physical} | {selected_max} | {dominant} | {flow} | {micro_R} | "
            "{micro_E} | {transition_R} | {transition_E} | {tail_R} | {tail_E} | "
            "{worst_post_R_mid_rg} | {first_regular_dx} | {Rson_rg} | {lambda0} | {int_adv} | "
            "{max_HR} | {a} | {g_u} | {g_T} | {nfev} | {success} | {message} |".format(
                R_join_rg=fmt(float(row["R_join_rg"])),
                transition_extent_requested=fmt(float(row["transition_extent_requested"])),
                stage=row["stage"],
                physical_active=fmt(float(row["physical_active"])),
                near_sonic_physical=fmt(float(row["near_sonic_physical"])),
                selected_max=fmt(float(row["selected_max"])),
                dominant=row["dominant"],
                flow=fmt(float(row["flow"])),
                micro_R=fmt(float(row["micro_R"])),
                micro_E=fmt(float(row["micro_E"])),
                transition_R=fmt(float(row["transition_R"])),
                transition_E=fmt(float(row["transition_E"])),
                tail_R=fmt(float(row["tail_R"])),
                tail_E=fmt(float(row["tail_E"])),
                worst_post_R_mid_rg=fmt(float(row["worst_post_R_mid_rg"])),
                first_regular_dx=fmt(float(row["first_regular_dx"])),
                Rson_rg=fmt(float(row["Rson_rg"])),
                lambda0=fmt(float(row["lambda0"])),
                int_adv=fmt(float(row["int_adv"])),
                max_HR=fmt(float(row["max_HR"])),
                a=fmt(float(row["a"])),
                g_u=fmt(float(row["g_u"])),
                g_T=fmt(float(row["g_T"])),
                nfev=row["nfev"],
                success="yes" if row["success"] else "no",
                message=str(row["message"]).replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    ctx = load_context()
    source_x, source_meta = load_row(SOURCE_CHECKPOINT)
    _fit_result, reverse_info = solve_fit(ctx, "fixed_buffer", None)
    logR_son = float(reverse_info["logR_son"])
    y_s = np.asarray(reverse_info["y_s"], dtype=float)
    lambda0 = float(reverse_info["lambda0"])
    branches = sonic_derivative_branches(
        logR_son,
        y_s,
        lambda0,
        ctx.params.physics,
        eps=LHOPITAL_EPS,
        form="scaled",
        half_width=BRANCH_HALF_WIDTH,
        scan_points=BRANCH_POINTS,
    )
    if BRANCH_INDEX >= len(branches):
        raise RuntimeError(f"branch {BRANCH_INDEX} unavailable; found {len(branches)}")
    branch = branches[BRANCH_INDEX]
    rows: list[dict[str, object]] = []
    for R_join_rg in R_JOIN_RG:
        base_params = make_params(
            fiducial,
            source_meta,
            N_REGULAR,
            EPSILON_BUF,
            BRANCH_INDEX,
            float(branch.a),
            mdot_edd,
            default_grid_config(),
        )
        transition_extent = transition_extent_for(logR_son, base_params, R_join_rg)
        if transition_extent <= 0.004:
            print(f"skip R_join={R_join_rg:g}: requested extent {transition_extent:.4g} is inside micro extent", flush=True)
            continue
        grid_config = replace(default_grid_config(), transition_extent=float(transition_extent))
        params = make_params(
            fiducial,
            source_meta,
            N_REGULAR,
            EPSILON_BUF,
            BRANCH_INDEX,
            float(branch.a),
            mdot_edd,
            grid_config,
        )
        label = f"short_join_R{R_join_rg:g}_branch{BRANCH_INDEX}_N{N_REGULAR}".replace(".", "p")
        seed = seed_profile(params, float(branch.a), reverse_info, ctx, source_x, SEED_MODE)
        seed_row = audit(label, seed, params, seed_mode=SEED_MODE, epsilon_buf=EPSILON_BUF, branch_index=BRANCH_INDEX)
        seed_row["stage"] = "seed"
        rows.append(row_for_table(seed_row, R_join_rg, transition_extent))
        write_table(rows)
        print(
            f"{label} seed physical={seed_row['physical_active']:.3e} near={seed_row['near_sonic_physical']:.3e} "
            f"dominant={seed_row['dominant']} trans={max(seed_row['transition_R'], seed_row['transition_E']):.3e} "
            f"tail={max(seed_row['tail_R'], seed_row['tail_E']):.3e}",
            flush=True,
        )
        release = solve_graded(seed, params, MAX_NFEV_RELEASE)
        release_row = audit(label, release.x, params, release, seed_mode=SEED_MODE, epsilon_buf=EPSILON_BUF, branch_index=BRANCH_INDEX)
        release_row["stage"] = "release"
        rows.append(row_for_table(release_row, R_join_rg, transition_extent))
        write_table(rows)
        print(
            f"{label} release physical={release_row['physical_active']:.3e} near={release_row['near_sonic_physical']:.3e} "
            f"dominant={release_row['dominant']} tail={max(release_row['tail_R'], release_row['tail_E']):.3e} "
            f"nfev={release.nfev}",
            flush=True,
        )
        polish = solve_graded(release.x, params, MAX_NFEV_POLISH)
        polish_row = audit(label, polish.x, params, polish, seed_mode=SEED_MODE, epsilon_buf=EPSILON_BUF, branch_index=BRANCH_INDEX)
        polish_row["stage"] = "polish"
        rows.append(row_for_table(polish_row, R_join_rg, transition_extent))
        write_table(rows)
        print(
            f"{label} polish physical={polish_row['physical_active']:.3e} near={polish_row['near_sonic_physical']:.3e} "
            f"dominant={polish_row['dominant']} tail={max(polish_row['tail_R'], polish_row['tail_E']):.3e} "
            f"nfev={polish.nfev}",
            flush=True,
        )
    write_table(rows)
    print(f"wrote {TABLE_OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
