"""Probe the staged transonic branch above the low-Mdot validation range."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    remap_profile_to_new_sonic_grid,
    solve_low_mdot_transonic_homotopy,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_high_rate_probe.md"


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def usable(status) -> bool:
    return bool(
        status.physically_valid
        or (
            status.optimizer_acceptable
            and status.equations_converged
            and status.sonic_regular
            and status.active_bounds_clear
            and status.outer_thin
        )
    )


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    ratios = [1.0e-3, 2.5e-3, 4.5e-3, 5.5e-3, 1.0e-2, 2.0e-2, 3.0e-2, 5.0e-2, 0.1]
    previous_profile = None
    rows = []
    for ratio in ratios:
        params = TransonicSlimParams(
            M2_g=fiducial.M2_g,
            Mdot_g_s=ratio * mdot_edd,
            alpha=fiducial.alpha_cool,
            n_nodes=24,
            R_out_rg=1000.0,
            max_nfev=1200,
            residual_tol=3.0e-4,
        )
        guess = remap_profile_to_new_sonic_grid(previous_profile, params) if previous_profile is not None else None
        result = solve_low_mdot_transonic_homotopy(
            params,
            initial_guess=guess,
            max_nfev_per_stage=700,
            final_max_nfev=1200,
        )
        final = result.final_result
        profile = final.profile
        audit = final.residual_audit
        status = final.status
        is_usable = usable(status)
        rows.append(
            {
                "ratio": ratio,
                "usable": is_usable,
                "physical": status.physically_valid,
                "equations": status.equations_converged,
                "sonic": status.sonic_regular,
                "thin_limit": status.thin_limit_ok,
                "lambda_ratio": audit.lambda0_over_lK_isco,
                "Rson_rg": profile.sonic_radius / params.r_g,
                "max_HR": float(np.max(profile.H_over_R)),
                "outer_HR": audit.outer_H_over_R,
                "max_residual": final.max_residual,
                "interval_radial": audit.interval_radial_max,
                "outer_omega": audit.outer_omega,
                "sonic_D": audit.sonic_D,
                "sonic_C1": audit.sonic_C1,
                "sonic_C2": audit.sonic_C2,
                "nfev": final.nfev,
                "message": final.message,
            }
        )
        print(
            f"ratio={ratio:g} usable={is_usable} physical={status.physically_valid} "
            f"lambda/lK={audit.lambda0_over_lK_isco:.4g} max={final.max_residual:.4g} "
            f"H/R={np.max(profile.H_over_R):.4g}",
            flush=True,
        )
        if is_usable or (status.sonic_regular and final.max_residual < 8.0e-4):
            previous_profile = profile

    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Transonic High-Rate Probe",
        "",
        "Generated by `scripts/run_transonic_high_rate_probe.py`.",
        "",
        "Configuration: `N=24`, `R_out=1000 r_g`, uniform log grid.",
        "",
        "| Mdot/Mdot_Edd | usable | physical | equations | sonic | thin limit | lambda/lK_ISCO | R_son/r_g | max H/R | outer H/R | max residual | interval R | outer Omega | D | C1 | C2 | nfev | message |",
        "|---:|:---:|:---:|:---:|:---:|:---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {ratio} | {usable} | {physical} | {equations} | {sonic} | {thin_limit} | "
            "{lambda_ratio} | {Rson_rg} | {max_HR} | {outer_HR} | {max_residual} | "
            "{interval_radial} | {outer_omega} | {sonic_D} | {sonic_C1} | {sonic_C2} | "
            "{nfev} | {message} |".format(
                ratio=fmt(row["ratio"]),
                usable="yes" if row["usable"] else "no",
                physical="yes" if row["physical"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                thin_limit="yes" if row["thin_limit"] else "no",
                lambda_ratio=fmt(row["lambda_ratio"]),
                Rson_rg=fmt(row["Rson_rg"]),
                max_HR=fmt(row["max_HR"]),
                outer_HR=fmt(row["outer_HR"]),
                max_residual=fmt(row["max_residual"]),
                interval_radial=fmt(row["interval_radial"]),
                outer_omega=fmt(row["outer_omega"]),
                sonic_D=fmt(row["sonic_D"]),
                sonic_C1=fmt(row["sonic_C1"]),
                sonic_C2=fmt(row["sonic_C2"]),
                nfev=row["nfev"],
                message=row["message"].replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
