"""Run a staged low-Mdot transonic homotopy audit."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    remap_profile_to_new_sonic_grid,
    solve_low_mdot_transonic_homotopy,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_homotopy_low_mdot.md"


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    ratios = [1.0e-3, 3.0e-3, 1.0e-2]
    rows = []
    previous_profile = None
    for ratio in ratios:
        params = TransonicSlimParams(
            M2_g=fiducial.M2_g,
            Mdot_g_s=ratio * mdot_edd,
            alpha=fiducial.alpha_cool,
            n_nodes=18,
            R_out_rg=300.0,
            max_nfev=1000,
            residual_tol=2.5e-4,
        )
        initial_guess = remap_profile_to_new_sonic_grid(previous_profile, params) if previous_profile is not None else None
        result = solve_low_mdot_transonic_homotopy(
            params,
            initial_guess=initial_guess,
            max_nfev_per_stage=600,
            final_max_nfev=1000,
        )
        final = result.final_result
        profile = final.profile
        audit = final.residual_audit
        status = final.status
        rows.append(
            {
                "ratio": ratio,
                "physical": status.physically_valid,
                "optimizer": status.optimizer_converged,
                "optimizer_ok": status.optimizer_acceptable,
                "equations": status.equations_converged,
                "sonic": status.sonic_regular,
                "lambda_ratio": audit.lambda0_over_lK_isco,
                "lambda0": profile.lambda0,
                "Rson_rg": profile.sonic_radius / params.r_g,
                "max_HR": float(np.max(profile.H_over_R)),
                "max_residual": final.max_residual,
                "interval_radial": audit.interval_radial_max,
                "interval_energy": audit.interval_energy_max,
                "outer_omega": audit.outer_omega,
                "outer_energy": audit.outer_energy,
                "sonic_D": audit.sonic_D,
                "sonic_C1": audit.sonic_C1,
                "sonic_C2": audit.sonic_C2,
                "smin": audit.sonic_smin_over_smax,
                "nfev": final.nfev,
                "stage_A": result.stages[0].max_residual,
                "stage_B": result.stages[1].max_residual,
                "message": final.message,
            }
        )
        print(
            f"Mdot/Mdot_Edd={ratio:g} physical={status.physically_valid} "
            f"lambda/lK={audit.lambda0_over_lK_isco:.4g} max_res={final.max_residual:.4g}",
            flush=True,
        )
        usable_seed = status.physically_valid or (
            status.equations_converged
            and status.sonic_regular
            and status.thin_limit_ok
            and status.active_bounds_clear
        )
        previous_profile = profile if usable_seed else previous_profile

    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Low-Mdot Transonic Homotopy Audit",
        "",
        "Generated by `scripts/run_transonic_homotopy_low_mdot.py`.",
        "",
        "This audit uses staged eigenparameter release: fixed profile solve, free `R_son` with fixed thin-disk `lambda0`, then the full scaled sonic compatibility solve.",
        "",
        "| Mdot/Mdot_Edd | physical | optimizer ok | optimizer raw | equations | sonic | lambda/lK_ISCO | lambda0 | R_son/r_g | max H/R | max residual | interval R | interval E | outer Omega | outer E | D | C1 | C2 | smin/smax | nfev | stage A max | stage B max | message |",
        "|---:|:---:|:---:|:---:|:---:|:---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {ratio:g} | {physical} | {optimizer_ok} | {optimizer} | {equations} | {sonic} | {lambda_ratio} | {lambda0} | "
            "{Rson_rg} | {max_HR} | {max_residual} | {interval_radial} | {interval_energy} | "
            "{outer_omega} | {outer_energy} | {sonic_D} | {sonic_C1} | {sonic_C2} | {smin} | "
            "{nfev} | {stage_A} | {stage_B} | {message} |".format(
                ratio=row["ratio"],
                physical="yes" if row["physical"] else "no",
                optimizer_ok="yes" if row["optimizer_ok"] else "no",
                optimizer="yes" if row["optimizer"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                lambda_ratio=fmt(row["lambda_ratio"]),
                lambda0=fmt(row["lambda0"]),
                Rson_rg=fmt(row["Rson_rg"]),
                max_HR=fmt(row["max_HR"]),
                max_residual=fmt(row["max_residual"]),
                interval_radial=fmt(row["interval_radial"]),
                interval_energy=fmt(row["interval_energy"]),
                outer_omega=fmt(row["outer_omega"]),
                outer_energy=fmt(row["outer_energy"]),
                sonic_D=fmt(row["sonic_D"]),
                sonic_C1=fmt(row["sonic_C1"]),
                sonic_C2=fmt(row["sonic_C2"]),
                smin=fmt(row["smin"]),
                nfev=row["nfev"],
                stage_A=fmt(row["stage_A"]),
                stage_B=fmt(row["stage_B"]),
                message=row["message"].replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
