"""Seed the smooth-a flow-map BVP from the reverse-fitted sonic point."""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d.transonic_local import sonic_derivative_branches
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot

from run_transonic_outer_slope_calibration_audit import fmt
from run_transonic_sonic_reverse_fit import SOURCE_CHECKPOINT, load_context, solve_fit
from run_transonic_two_domain_dynamic_sonic_patch import load_row
from run_transonic_two_domain_sonic_refinement_sprint import buffer_inner_grid, unpack_buffer
from run_transonic_two_domain_sonic_flowmap import (
    CHECKPOINT_DIR,
    flow_inner_grid,
    make_flowmap_params,
    outer_grid,
    pack_flowmap,
    pack_smooth_flowmap,
    pchip_extrap,
    save_checkpoint,
    smooth_flowmap_audit,
    solve_smooth_flowmap,
)


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_reverse_seed_flowmap_bvp.md"
N_SEQUENCE = tuple(int(piece) for piece in os.environ.get("IMBH_REVERSE_BVP_N_SEQUENCE", "16").replace(":", ",").split(",") if piece.strip())
BRANCH_SEQUENCE = tuple(int(piece) for piece in os.environ.get("IMBH_REVERSE_BVP_BRANCHES", "0,1").replace(":", ",").split(",") if piece.strip())
MAX_NFEV_RELEASE = int(os.environ.get("IMBH_REVERSE_BVP_MAX_NFEV_RELEASE", "120"))
MAX_NFEV_POLISH = int(os.environ.get("IMBH_REVERSE_BVP_MAX_NFEV_POLISH", "60"))
BRANCH_HALF_WIDTH = float(os.environ.get("IMBH_REVERSE_BVP_BRANCH_HALF_WIDTH", "1000"))
BRANCH_POINTS = int(os.environ.get("IMBH_REVERSE_BVP_BRANCH_POINTS", "2001"))


def reverse_seed(params, branch_a: float, reverse_info: dict[str, object], ctx, source_x: np.ndarray) -> np.ndarray:
    logu_i_old, logT_i_old, logu_o_old, logT_o_old, logR_son_old, _lambda_old = unpack_buffer(source_x, ctx.params)
    logR_i_old = buffer_inner_grid(logR_son_old, ctx.params)
    logR_o_old = outer_grid(ctx.params)  # type: ignore[arg-type]
    logR_son = float(reverse_info["logR_son"])
    lambda0 = float(reverse_info["lambda0"])
    y_s = np.asarray(reverse_info["y_s"], dtype=float)
    y_buffer = np.asarray(reverse_info["y_buffer"], dtype=float)
    logR_i_new = flow_inner_grid(logR_son, params)
    logR_o_new = outer_grid(params)  # type: ignore[arg-type]

    logu_i_new = pchip_extrap(logR_i_old, logu_i_old, logR_i_new)
    logT_i_new = pchip_extrap(logR_i_old, logT_i_old, logR_i_new)
    logu_i_new[0] = float(y_buffer[0])
    logT_i_new[0] = float(y_buffer[1])

    logu_o_new = pchip_extrap(logR_o_old, logu_o_old, logR_o_new)
    logT_o_new = pchip_extrap(logR_o_old, logT_o_old, logR_o_new)
    logu_o_new[0] = float(logu_i_new[-1])
    logT_o_new[0] = float(logT_i_new[-1])
    base = pack_flowmap(y_s, logu_i_new, logT_i_new, logu_o_new, logT_o_new, logR_son, lambda0)
    return pack_smooth_flowmap(base, branch_a)


def write_table(rows: list[dict[str, object]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Reverse-Seeded Smooth-a Flow-Map BVP",
        "",
        "Generated by `scripts/run_transonic_reverse_seed_flowmap_bvp.py`.",
        "",
        "| label | stage | branch | N regular | physical | selected | dominant | D | C1 | C2 | K | L | flow | regular R | regular E | outer R | outer E | far omega | Rson/rg | lambda0 | int adv | max H/R | a | g_u | g_T | nfev | success | message |",
        "|---|---|---:|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {label} | {stage} | {branch} | {n_regular} | {physical_active} | {selected_max} | {dominant} | "
            "{D} | {C1} | {C2} | {K} | {L} | {flow} | {regular_R} | {regular_E} | {outer_R} | {outer_E} | "
            "{far_omega} | {Rson_rg} | {lambda0} | {int_adv} | {max_HR} | {a} | {g_u} | {g_T} | {nfev} | {success} | {message} |".format(
                label=row["label"],
                stage=row["stage"],
                branch=row["branch"],
                n_regular=row["n_regular"],
                physical_active=fmt(float(row["physical_active"])),
                selected_max=fmt(float(row["selected_max"])),
                dominant=row["dominant"],
                D=fmt(float(row["D"])),
                C1=fmt(float(row["C1"])),
                C2=fmt(float(row["C2"])),
                K=fmt(float(row["K"])),
                L=fmt(float(row["L"])),
                flow=fmt(float(row["flow"])),
                regular_R=fmt(float(row["regular_R"])),
                regular_E=fmt(float(row["regular_E"])),
                outer_R=fmt(float(row["outer_R"])),
                outer_E=fmt(float(row["outer_E"])),
                far_omega=fmt(float(row["far_omega"])),
                Rson_rg=fmt(float(row["Rson_rg"])),
                lambda0=fmt(float(row["lambda0"])),
                int_adv=fmt(float(row["int_adv"])),
                max_HR=fmt(float(row["max_HR"])),
                a=fmt(float(row["a"])),
                g_u=fmt(float(row["g_u"])),
                g_T=fmt(float(row["g_T"])),
                nfev=row["nfev"],
                success="yes" if row["success"] else "no",
                message=str(row["message"]).replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    ctx = load_context()
    source_x, source_meta = load_row(SOURCE_CHECKPOINT)
    fit_result, reverse_info = solve_fit(ctx, "fixed_buffer", None)
    dx = float(reverse_info["dx"])
    branches = sonic_derivative_branches(
        float(reverse_info["logR_son"]),
        np.asarray(reverse_info["y_s"], dtype=float),
        float(reverse_info["lambda0"]),
        ctx.params.physics,
        eps=1.0e-5,
        form="scaled",
        half_width=BRANCH_HALF_WIDTH,
        scan_points=BRANCH_POINTS,
    )
    if not branches:
        raise RuntimeError("reverse-fitted sonic point has no L'Hopital branches")
    print(
        f"reverse-seeded BVP dx={dx:.6g} Rson={float(reverse_info['Rson_rg']):.6g} "
        f"lambda={float(reverse_info['lambda0']):.6g} branches={len(branches)}",
        flush=True,
    )
    rows: list[dict[str, object]] = []
    for branch_index in BRANCH_SEQUENCE:
        if branch_index >= len(branches):
            continue
        branch = branches[branch_index]
        current_x = None
        current_params = None
        for n_regular in N_SEQUENCE:
            params = make_flowmap_params(
                fiducial,
                float(source_meta["ratio"]),
                mdot_edd,
                int(n_regular),
                int(source_meta["n_outer"]),
                float(source_meta["R_far_rg"]),
                dx,
                branch_index,
                float(branch.a),
            )
            if current_x is None or current_params is None:
                seed = reverse_seed(params, float(branch.a), reverse_info, ctx, source_x)
            else:
                from run_transonic_two_domain_sonic_flowmap import smooth_seed_from_smooth

                seed = smooth_seed_from_smooth(current_x, current_params, params)
            label = f"reverse_branch{branch_index}_N{n_regular}"
            seed_row = smooth_flowmap_audit(label, seed, params)
            seed_row["stage"] = "seed"
            rows.append(seed_row)
            write_table(rows)
            print(f"{label} seed physical={seed_row['physical_active']:.3e} dominant={seed_row['dominant']} a={seed_row['a']:.4g}", flush=True)

            release = solve_smooth_flowmap(seed, params, MAX_NFEV_RELEASE)
            release_row = smooth_flowmap_audit(label, release.x, params, release)
            release_row["stage"] = "release"
            rows.append(release_row)
            write_table(rows)
            print(f"{label} release physical={release_row['physical_active']:.3e} dominant={release_row['dominant']} nfev={release.nfev}", flush=True)

            polish = solve_smooth_flowmap(release.x, params, MAX_NFEV_POLISH)
            polish_row = smooth_flowmap_audit(label, polish.x, params, polish)
            polish_row["stage"] = "polish"
            rows.append(polish_row)
            write_table(rows)
            save_checkpoint(f"reverse_{label}", np.asarray(polish_row["x"], dtype=float), polish_row)
            print(f"{label} polish physical={polish_row['physical_active']:.3e} dominant={polish_row['dominant']} nfev={polish.nfev}", flush=True)
            current_x = np.asarray(polish_row["x"], dtype=float)
            current_params = params
    write_table(rows)
    print(f"wrote {TABLE_OUTPUT}", flush=True)
    print(f"checkpoints in {CHECKPOINT_DIR}", flush=True)


if __name__ == "__main__":
    main()
