"""Outer-boundary and resolution sweep for the transonic homotopy branch."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    remap_profile_to_new_sonic_grid,
    solve_low_mdot_transonic_homotopy,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_outer_boundary_sweep.md"
WARMUP_RATIOS = (1.0e-3, 2.5e-3, 5.0e-3, 1.0e-2, 2.0e-2, 3.0e-2)
TARGET_SEED_RATIO = 5.0e-2
TARGET_RATIO = 0.1
WARMUP_SONIC_WEIGHTS = (1.0,)
TARGET_SONIC_WEIGHTS = (0.3, 1.0, 3.0)
RESIDUAL_TOL = 3.0e-4


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def usable(status) -> bool:
    return bool(
        status.physically_valid
        or (
            status.optimizer_acceptable
            and status.equations_converged
            and status.sonic_regular
            and status.active_bounds_clear
            and status.outer_thin
        )
    )


def dominant_block(audit) -> str:
    values = {
        "interval_R": abs(audit.interval_radial_max),
        "interval_E": abs(audit.interval_energy_max),
        "outer_Omega": abs(audit.outer_omega),
        "outer_E": abs(audit.outer_energy),
        "D": abs(audit.sonic_D),
        "C1": abs(audit.sonic_C1),
        "C2": abs(audit.sonic_C2),
    }
    return max(values, key=values.get)


def solve_one(
    *,
    M2_g: float,
    mdot_edd: float,
    alpha: float,
    ratio: float,
    n_nodes: int,
    R_out_rg: float,
    seed_profile,
    sonic_weight_sequence: tuple[float, ...],
):
    params = TransonicSlimParams(
        M2_g=M2_g,
        Mdot_g_s=ratio * mdot_edd,
        alpha=alpha,
        n_nodes=n_nodes,
        R_out_rg=R_out_rg,
        max_nfev=1200,
        residual_tol=RESIDUAL_TOL,
    )
    guess = remap_profile_to_new_sonic_grid(seed_profile, params) if seed_profile is not None else None
    result = solve_low_mdot_transonic_homotopy(
        params,
        initial_guess=guess,
        max_nfev_per_stage=700,
        final_max_nfev=1200,
        sonic_weight_sequence=sonic_weight_sequence,
    )
    return params, result


def row_from_result(label: str, ratio: float, n_nodes: int, R_out_rg: float, params, result, seed_usable: bool | None = None) -> dict[str, object]:
    final = result.final_result
    profile = final.profile
    audit = final.residual_audit
    status = final.status
    b2_stages = [stage for stage in result.stages if stage.name.startswith("B2_")]
    return {
        "label": label,
        "ratio": ratio,
        "n_nodes": n_nodes,
        "R_out_rg": R_out_rg,
        "usable": usable(status),
        "seed_usable": seed_usable,
        "physical": status.physically_valid,
        "equations": status.equations_converged,
        "sonic": status.sonic_regular,
        "dominant": dominant_block(audit),
        "lambda_ratio": audit.lambda0_over_lK_isco,
        "Rson_rg": profile.sonic_radius / params.r_g,
        "max_HR": float(np.max(profile.H_over_R)),
        "outer_HR": audit.outer_H_over_R,
        "outer_Qadv_over_Qvisc": audit.outer_Qadv_over_Qvisc,
        "max_residual": final.max_residual,
        "interval_radial": audit.interval_radial_max,
        "interval_energy": audit.interval_energy_max,
        "outer_omega": audit.outer_omega,
        "outer_energy": audit.outer_energy,
        "sonic_D": audit.sonic_D,
        "sonic_C1": audit.sonic_C1,
        "sonic_C2": audit.sonic_C2,
        "stage_B2_last": b2_stages[-1].max_residual if b2_stages else np.nan,
        "nfev": final.nfev,
        "message": final.message,
    }


def write_table(rows: list[dict[str, object]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Transonic Outer-Boundary Sweep",
        "",
        "Generated by `scripts/run_transonic_outer_boundary_sweep.py`.",
        "",
        f"Target: `Mdot/Mdot_Edd={TARGET_RATIO:g}`. Each target solve is seeded by an `Mdot/Mdot_Edd={TARGET_SEED_RATIO:g}` solve at the same `(N, R_out)`.",
        "",
        "| label | N | R_out/r_g | Mdot/Mdot_Edd | usable | seed usable | physical | equations | sonic | dominant | lambda/lK_ISCO | R_son/r_g | max H/R | outer H/R | outer Qadv/Qvisc | max residual | interval R | interval E | outer Omega | outer E | D | C1 | C2 | B2 max | nfev | message |",
        "|---|---:|---:|---:|:---:|:---:|:---:|:---:|:---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        seed_usable = row["seed_usable"]
        lines.append(
            "| {label} | {n_nodes} | {R_out_rg} | {ratio} | {usable} | {seed_usable} | "
            "{physical} | {equations} | {sonic} | {dominant} | {lambda_ratio} | {Rson_rg} | "
            "{max_HR} | {outer_HR} | {outer_Qadv_over_Qvisc} | {max_residual} | "
            "{interval_radial} | {interval_energy} | {outer_omega} | {outer_energy} | "
            "{sonic_D} | {sonic_C1} | {sonic_C2} | {stage_B2_last} | {nfev} | {message} |".format(
                label=row["label"],
                n_nodes=row["n_nodes"],
                R_out_rg=fmt(float(row["R_out_rg"])),
                ratio=fmt(float(row["ratio"])),
                usable="yes" if row["usable"] else "no",
                seed_usable="n/a" if seed_usable is None else ("yes" if seed_usable else "no"),
                physical="yes" if row["physical"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                dominant=row["dominant"],
                lambda_ratio=fmt(float(row["lambda_ratio"])),
                Rson_rg=fmt(float(row["Rson_rg"])),
                max_HR=fmt(float(row["max_HR"])),
                outer_HR=fmt(float(row["outer_HR"])),
                outer_Qadv_over_Qvisc=fmt(float(row["outer_Qadv_over_Qvisc"])),
                max_residual=fmt(float(row["max_residual"])),
                interval_radial=fmt(float(row["interval_radial"])),
                interval_energy=fmt(float(row["interval_energy"])),
                outer_omega=fmt(float(row["outer_omega"])),
                outer_energy=fmt(float(row["outer_energy"])),
                sonic_D=fmt(float(row["sonic_D"])),
                sonic_C1=fmt(float(row["sonic_C1"])),
                sonic_C2=fmt(float(row["sonic_C2"])),
                stage_B2_last=fmt(float(row["stage_B2_last"])),
                nfev=row["nfev"],
                message=str(row["message"]).replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    rows: list[dict[str, object]] = []

    warmup_seed = None
    for ratio in WARMUP_RATIOS:
        params, result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=24,
            R_out_rg=1000.0,
            seed_profile=warmup_seed,
            sonic_weight_sequence=WARMUP_SONIC_WEIGHTS,
        )
        row = row_from_result("warmup", ratio, 24, 1000.0, params, result)
        rows.append(row)
        write_table(rows)
        print(
            f"warmup rate={ratio:g} usable={row['usable']} max={row['max_residual']:.4g} "
            f"dominant={row['dominant']}",
            flush=True,
        )
        if bool(row["usable"]) or (result.final_result.status.sonic_regular and result.final_result.max_residual < 8.0e-4):
            warmup_seed = result.final_result.profile

    configs = [(n_nodes, R_out_rg) for R_out_rg in (300.0, 1000.0, 3000.0) for n_nodes in (32, 48, 64)]
    for n_nodes, R_out_rg in configs:
        seed_params, seed_result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=TARGET_SEED_RATIO,
            n_nodes=n_nodes,
            R_out_rg=R_out_rg,
            seed_profile=warmup_seed,
            sonic_weight_sequence=TARGET_SONIC_WEIGHTS,
        )
        seed_row = row_from_result("target_seed", TARGET_SEED_RATIO, n_nodes, R_out_rg, seed_params, seed_result)
        rows.append(seed_row)
        write_table(rows)
        print(
            f"seed N={n_nodes} Rout={R_out_rg:g} usable={seed_row['usable']} "
            f"max={seed_row['max_residual']:.4g} dominant={seed_row['dominant']}",
            flush=True,
        )

        seed_profile = seed_result.final_result.profile
        target_params, target_result = solve_one(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=TARGET_RATIO,
            n_nodes=n_nodes,
            R_out_rg=R_out_rg,
            seed_profile=seed_profile,
            sonic_weight_sequence=TARGET_SONIC_WEIGHTS,
        )
        target_row = row_from_result(
            "target",
            TARGET_RATIO,
            n_nodes,
            R_out_rg,
            target_params,
            target_result,
            seed_usable=bool(seed_row["usable"]),
        )
        rows.append(target_row)
        write_table(rows)
        print(
            f"target N={n_nodes} Rout={R_out_rg:g} usable={target_row['usable']} "
            f"max={target_row['max_residual']:.4g} outer={target_row['outer_omega']:.4g} "
            f"D={target_row['sonic_D']:.4g} dominant={target_row['dominant']}",
            flush=True,
        )

    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
