"""Audit square transonic collocation Jacobians against directional differences."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import TransonicSlimParams, jacobian_directional_error
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
CHECKPOINT_DIR = ROOT / "outputs" / "checkpoints" / "transonic_n64_arclength_adaptive"
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_square_jacobian_audit.md"
STEPS = (1.0e-3, 3.0e-4, 1.0e-4, 3.0e-5, 1.0e-5, 3.0e-6, 1.0e-6)
TARGET_RATIOS = (0.3, 0.7, 0.95, 1.0)


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def checkpoint_records() -> list[tuple[float, Path]]:
    records: list[tuple[float, Path]] = []
    for path in sorted(CHECKPOINT_DIR.glob("*.npz")):
        with np.load(path, allow_pickle=False) as data:
            records.append((float(data["ratio"]), path))
    return records


def nearest_checkpoints(targets: tuple[float, ...]) -> list[Path]:
    records = checkpoint_records()
    if not records:
        raise RuntimeError(f"no checkpoints found in {CHECKPOINT_DIR}")
    selected: list[Path] = []
    seen: set[Path] = set()
    for target in targets:
        _ratio, path = min(records, key=lambda item: abs(item[0] - target))
        if path not in seen:
            selected.append(path)
            seen.add(path)
    return selected


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    rows = []
    for path in nearest_checkpoints(TARGET_RATIOS):
        with np.load(path, allow_pickle=False) as data:
            z = np.asarray(data["z"], dtype=float)
            ratio = float(data["ratio"])
        params = TransonicSlimParams(
            M2_g=fiducial.M2_g,
            Mdot_g_s=ratio * mdot_edd,
            alpha=fiducial.alpha_cool,
            n_nodes=64,
            R_out_rg=3000.0,
            residual_tol=3.0e-4,
        )
        audit = jacobian_directional_error(
            z,
            params,
            steps=STEPS,
            n_directions=4,
            seed=11,
            jacobian_rel_step=3.0e-5,
        )
        best_index = int(np.argmin(audit.median_relative_error))
        rows.append(
            {
                "checkpoint": path.name,
                "ratio": ratio,
                "pivot": audit.pivot,
                "best_step": audit.best_step,
                "best_median": audit.best_median_error,
                "best_max": float(audit.max_relative_error[best_index]),
                "median_1e3": float(audit.median_relative_error[0]),
                "median_3e5": float(audit.median_relative_error[3]),
                "median_1e6": float(audit.median_relative_error[-1]),
            }
        )
        print(
            f"{path.name} ratio={ratio:.4g} pivot={audit.pivot} "
            f"best_h={audit.best_step:.1e} median={audit.best_median_error:.3e}",
            flush=True,
        )

    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Square Transonic Jacobian Directional Audit",
        "",
        "Generated by `scripts/run_transonic_square_jacobian_audit.py`.",
        "",
        "The audit uses the square residual with `D` plus one pivoted sonic compatibility equation.",
        "",
        "| checkpoint | Mdot/Mdot_Edd | pivot | best h | median error at best h | max error at best h | median h=1e-3 | median h=3e-5 | median h=1e-6 |",
        "|---|---:|:---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            "| {checkpoint} | {ratio} | {pivot} | {best_step} | {best_median} | {best_max} | "
            "{median_1e3} | {median_3e5} | {median_1e6} |".format(
                checkpoint=row["checkpoint"],
                ratio=fmt(row["ratio"]),
                pivot=row["pivot"],
                best_step=fmt(row["best_step"]),
                best_median=fmt(row["best_median"]),
                best_max=fmt(row["best_max"]),
                median_1e3=fmt(row["median_1e3"]),
                median_3e5=fmt(row["median_3e5"]),
                median_1e6=fmt(row["median_1e6"]),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
