"""Focused high-iteration polish for the best tuned full-slope checkpoint."""

from __future__ import annotations

import numpy as np

import run_transonic_full_slope_tuned_sonic_audit as tuned
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot
from run_transonic_full_slope_sensitivity_audit import (
    SLOPE_SOURCE_CHECKPOINT,
    load_checkpoint,
    polyfit_outer_log_slopes,
)


ROOT = tuned.ROOT
SOURCE_CHECKPOINT = (
    ROOT
    / "outputs"
    / "checkpoints"
    / "transonic_full_slope_tuned_sonic_audit"
    / "g_T_plus_1e-3_symmetric_D_C1_C2_0p90277664.npz"
)
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_full_slope_best_polish.md"
CHECKPOINT_OUTPUT = (
    ROOT
    / "outputs"
    / "checkpoints"
    / "transonic_full_slope_best_polish"
    / "g_T_plus_1e-3_symmetric_D_C1_C2_0p90277664.npz"
)
MAX_NFEV = 1500


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def write_table(row: dict[str, object]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Best Tuned Full-Slope Polish",
        "",
        "Generated by `scripts/run_transonic_full_slope_best_polish.py`.",
        "",
        "Starts from the best tuned symmetric sonic checkpoint and reruns the same residual system with a higher evaluation cap.",
        "",
        "| slope label | sonic label | max nfev | selected final | final physical | dominant | interval R | interval E | outer 1 | outer 2 | D | C1 | C2 | K | compat max | nfev | success | message |",
        "|---|---|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|---|",
        "| {label} | {sonic_label} | {max_nfev} | {final_selected} | {final_physical} | {dominant} | "
        "{interval_R} | {interval_E} | {outer_1} | {outer_2} | {D} | {C1} | {C2} | {K} | "
        "{compat_max} | {nfev} | {success} | {message} |".format(
            label=row["label"],
            sonic_label=row["sonic_label"],
            max_nfev=MAX_NFEV,
            final_selected=fmt(float(row["final_selected"])),
            final_physical=fmt(float(row["final_physical"])),
            dominant=row["dominant"],
            interval_R=fmt(float(row["interval_R"])),
            interval_E=fmt(float(row["interval_E"])),
            outer_1=fmt(float(row["outer_1"])),
            outer_2=fmt(float(row["outer_2"])),
            D=fmt(float(row["D"])),
            C1=fmt(float(row["C1"])),
            C2=fmt(float(row["C2"])),
            K=fmt(float(row["K"])),
            compat_max=fmt(float(row["compat_max"])),
            nfev=row["nfev"],
            success="yes" if row["success"] else "no",
            message=str(row["message"]).replace("|", "/"),
        ),
    ]
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")


def save_checkpoint(row: dict[str, object]) -> None:
    CHECKPOINT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = {key: value for key, value in row.items() if key != "z"}
    np.savez_compressed(
        CHECKPOINT_OUTPUT,
        z=np.asarray(row["z"], dtype=float),
        ratio=np.array(row["ratio"]),
        row_json=np.array(tuned.row_json(payload)),
    )


def main() -> None:
    tuned.MAX_NFEV = MAX_NFEV
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    slope_z, ratio = load_checkpoint(SLOPE_SOURCE_CHECKPOINT)
    slope_params = tuned.params_for(fiducial, mdot_edd, ratio, slopes=(0.0, 0.0))
    base_slopes = polyfit_outer_log_slopes(slope_z, slope_params)
    slopes = (base_slopes[0], base_slopes[1] + 1.0e-3)

    seed_z, seed_ratio = load_checkpoint(SOURCE_CHECKPOINT)
    if not np.isclose(seed_ratio, ratio):
        raise RuntimeError("seed checkpoint ratio mismatch")

    params = tuned.params_for(fiducial, mdot_edd, ratio, slopes=slopes)
    result = tuned.solve_variant(seed_z, params, "symmetric", "C1", ("D", "C1", "C2"))
    row = tuned.row_from_result(
        "g_T_plus_1e-3",
        "symmetric_D_C1_C2_polish",
        "symmetric",
        "C1",
        ("D", "C1", "C2"),
        ratio,
        params,
        seed_z,
        result,
    )
    save_checkpoint(row)
    write_table(row)
    print(
        f"final={row['final_physical']:.3e} dom={row['dominant']} nfev={row['nfev']} success={row['success']}",
        flush=True,
    )
    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
