"""Audit stream-source and wind-sink Mdot sign conventions."""

from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    mdot_profile_from_source_sink,
    stream_source_prime,
    wind_sink_prime,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot
from run_standard_slim_analytic_seed_audit import ALPHA, fmt, json_safe


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs/tables/stream_source_sink_bookkeeping_audit.md"
JSON_OUTPUT = TABLE_OUTPUT.with_suffix(".json")


def base_params() -> TransonicSlimParams:
    fiducial = FiducialParams()
    return TransonicSlimParams(
        M2_g=fiducial.M2_g,
        Mdot_g_s=eddington_mdot(fiducial.M2_g),
        alpha=ALPHA,
        R_out_rg=300.0,
        n_nodes=64,
        stream_source_center_fraction=0.8,
        stream_source_log_width=0.08,
        wind_sink_center_fraction=0.9,
        wind_sink_log_width=0.06,
    )


def audit_case(label: str, params: TransonicSlimParams, n_grid: int = 20001) -> dict[str, object]:
    logR = np.linspace(np.log(params.R_son_bounds_rg[0] * params.r_g), np.log(params.R_out), n_grid)
    mdot = np.asarray([mdot_profile_from_source_sink(float(x), params)[0] for x in logR], dtype=float)
    dmdot = np.asarray([mdot_profile_from_source_sink(float(x), params)[1] for x in logR], dtype=float)
    source = np.asarray([stream_source_prime(float(x), params) for x in logR], dtype=float)
    wind = np.asarray([wind_sink_prime(float(x), params) for x in logR], dtype=float)
    budget_integral = float(np.trapezoid(wind - source, logR))
    source_integral = float(np.trapezoid(source, logR))
    wind_integral = float(np.trapezoid(wind, logR))
    mdot_delta = float(mdot[-1] - mdot[0])
    budget_error = float(mdot_delta - budget_integral)
    scale = max(abs(mdot_delta), abs(budget_integral), abs(params.Mdot_g_s), 1.0)
    return {
        "case": label,
        "stream_source_fraction": float(params.stream_source_fraction),
        "legacy_stream_mass_fraction": float(params.stream_mass_fraction),
        "wind_sink_fraction": float(params.wind_sink_fraction),
        "Mdot_inner_over_param": float(mdot[0] / params.Mdot_g_s),
        "Mdot_outer_over_param": float(mdot[-1] / params.Mdot_g_s),
        "dMdot_outer_minus_inner_over_param": float(mdot_delta / params.Mdot_g_s),
        "source_integral_over_param": float(source_integral / params.Mdot_g_s),
        "wind_integral_over_param": float(wind_integral / params.Mdot_g_s),
        "max_source_prime_over_param": float(np.max(source) / params.Mdot_g_s),
        "max_wind_prime_over_param": float(np.max(wind) / params.Mdot_g_s),
        "min_signed_derivative_over_param": float(np.min(dmdot) / params.Mdot_g_s),
        "max_signed_derivative_over_param": float(np.max(dmdot) / params.Mdot_g_s),
        "budget_error_over_param": float(budget_error / params.Mdot_g_s),
        "relative_budget_error": float(abs(budget_error) / scale),
        "passes_1e6": bool(abs(budget_error) / scale < 1.0e-6),
    }


def write_table(rows: list[dict[str, object]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Stream Source/Sink Bookkeeping Audit",
        "",
        "Generated by `scripts/run_stream_source_sink_bookkeeping_audit.py`.",
        "",
        "Inward accretion rate is positive.  A positive stream source must make `dMdot/dlnR < 0` in the source annulus and `Mdot_outer < Mdot_inner`; a wind sink has the opposite sign.",
        "",
        "| case | source frac | legacy mass frac | wind frac | Mdot inner/param | Mdot outer/param | Delta Mdot/param | int source/param | int wind/param | min dMdot/param | max dMdot/param | rel budget err | pass |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|",
    ]
    for row in rows:
        formatted = {key: fmt(value) if isinstance(value, (float, int, np.floating, np.integer)) else value for key, value in row.items()}
        lines.append(
            "| {case} | {stream_source_fraction} | {legacy_stream_mass_fraction} | {wind_sink_fraction} | "
            "{Mdot_inner_over_param} | {Mdot_outer_over_param} | {dMdot_outer_minus_inner_over_param} | "
            "{source_integral_over_param} | {wind_integral_over_param} | {min_signed_derivative_over_param} | "
            "{max_signed_derivative_over_param} | {relative_budget_error} | {passes_1e6} |".format(**formatted)
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")
    JSON_OUTPUT.write_text(json.dumps(json_safe(rows), indent=2, sort_keys=True) + "\n")


def main() -> None:
    base = base_params()
    rows = [
        audit_case("none", base),
        audit_case("source_explicit_0p03", replace(base, stream_source_fraction=0.03)),
        audit_case("source_legacy_0p03", replace(base, stream_mass_fraction=0.03)),
        audit_case("wind_0p02", replace(base, wind_sink_fraction=0.02)),
        audit_case("mixed_source_0p05_wind_0p02", replace(base, stream_source_fraction=0.05, wind_sink_fraction=0.02)),
    ]
    write_table(rows)
    for row in rows:
        print(
            f"{row['case']}: Mout/Min={float(row['Mdot_outer_over_param']) / float(row['Mdot_inner_over_param']):.6g} "
            f"rel_budget={float(row['relative_budget_error']):.3e}",
            flush=True,
        )
    print(f"wrote {TABLE_OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
