"""Smoke-test square-residual pseudo-arclength steps above Eddington."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import TransonicSlimParams, pseudo_arclength_step
from imri_qpe.layer3_minidisk_1d.transonic_collocation import profile_from_state_vector
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
CHECKPOINT_DIR = ROOT / "outputs" / "checkpoints" / "transonic_n64_arclength_adaptive"
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_square_arclength_smoke.md"
SEED_FILES = (
    "032_arc_x1_0p96532914.npz",
    "033_arc_x1_0p99629052.npz",
)
CASES = (
    ("small", 0.25, 5),
    ("medium", 0.5, 5),
    ("large", 1.0, 5),
    ("medium_polish", 0.5, 20),
    ("large_polish", 1.0, 100),
)


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def load_seed_profiles(fiducial: FiducialParams, mdot_edd: float):
    profiles = []
    ratios = []
    for filename in SEED_FILES:
        path = CHECKPOINT_DIR / filename
        with np.load(path, allow_pickle=False) as data:
            z = np.asarray(data["z"], dtype=float)
            ratio = float(data["ratio"])
        params = TransonicSlimParams(
            M2_g=fiducial.M2_g,
            Mdot_g_s=ratio * mdot_edd,
            alpha=fiducial.alpha_cool,
            n_nodes=64,
            R_out_rg=3000.0,
            residual_tol=3.0e-4,
            max_nfev=50,
        )
        profiles.append(profile_from_state_vector(z, params))
        ratios.append(ratio)
    return profiles, ratios


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    profiles, ratios = load_seed_profiles(fiducial, mdot_edd)
    base_params = TransonicSlimParams(
        M2_g=fiducial.M2_g,
        Mdot_g_s=mdot_edd,
        alpha=fiducial.alpha_cool,
        n_nodes=64,
        R_out_rg=3000.0,
        residual_tol=3.0e-4,
        max_nfev=50,
    )

    rows = []
    for label, step_multiplier, max_nfev in CASES:
        result = pseudo_arclength_step(
            base_params,
            mdot_edd,
            profiles[0],
            ratios[0],
            profiles[1],
            ratios[1],
            step_multiplier=step_multiplier,
            mdot_ratio_bounds=(1.0e-4, 2.0),
            max_nfev=max_nfev,
            residual_tol=3.0e-4,
            arclength_weight=1.0,
            residual_mode="square",
            sonic_pivot="K",
            metric_mode="blockwise",
            tangent_mode="jacobian",
        )
        rows.append(
            {
                "label": label,
                "step_multiplier": step_multiplier,
                "max_nfev": max_nfev,
                "predicted": result.predicted_mdot_ratio,
                "ratio": result.mdot_ratio,
                "physical": result.status.physically_valid,
                "equations": result.status.equations_converged,
                "sonic": result.status.sonic_regular,
                "max_residual": result.max_residual,
                "arc": result.arclength_residual,
                "interval_R": result.residual_audit.interval_radial_max,
                "interval_E": result.residual_audit.interval_energy_max,
                "outer_Omega": result.residual_audit.outer_omega,
                "outer_E": result.residual_audit.outer_energy,
                "D": result.residual_audit.sonic_D,
                "K": result.residual_audit.sonic_K,
                "C1": result.residual_audit.sonic_C1,
                "C2": result.residual_audit.sonic_C2,
                "nfev": result.nfev,
                "corrector": result.corrector_method,
                "iterations": result.corrector_iterations,
                "njev": result.jacobian_evaluations,
                "cuts": result.line_search_reductions,
                "cond": result.condition_estimate,
                "pred_err": result.predictor_correction_norm,
                "tangent": result.tangent_audit.method,
                "optimizer_success": result.optimizer_success,
                "message": result.message,
            }
        )
        print(
            f"{label}: predicted={result.predicted_mdot_ratio:.6g} got={result.mdot_ratio:.6g} "
            f"physical={result.status.physically_valid} max={result.max_residual:.3e} "
            f"corrector={result.corrector_method} nfev={result.nfev}",
            flush=True,
        )

    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Square Pseudo-Arclength Smoke Test",
        "",
        "Generated by `scripts/run_transonic_square_arclength_smoke.py`.",
        "",
        "Rows start from the last two accepted N=64 adaptive arclength checkpoints and rerun one corrector step with the square sonic residual system.",
        "",
        "| label | step multiplier | max nfev | predicted Mdot/Edd | solved Mdot/Edd | physical | equations | sonic | max residual | arc residual | interval R | interval E | outer Omega | outer E | D | K | C1 | C2 | tangent | corrector | iter | cuts | cond | pred err | nfev | opt raw | message |",
        "|---|---:|---:|---:|---:|:---:|:---:|:---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|---|---:|---:|---:|---:|---:|:---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {label} | {step_multiplier} | {max_nfev} | {predicted} | {ratio} | {physical} | "
            "{equations} | {sonic} | {max_residual} | {arc} | {interval_R} | {interval_E} | "
            "{outer_Omega} | {outer_E} | {D} | {K} | {C1} | {C2} | {tangent} | "
            "{corrector} | {iterations} | {cuts} | {cond} | {pred_err} | {nfev} | {optimizer_success} | {message} |".format(
                label=row["label"],
                step_multiplier=fmt(row["step_multiplier"]),
                max_nfev=row["max_nfev"],
                predicted=fmt(row["predicted"]),
                ratio=fmt(row["ratio"]),
                physical="yes" if row["physical"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                max_residual=fmt(row["max_residual"]),
                arc=fmt(row["arc"]),
                interval_R=fmt(row["interval_R"]),
                interval_E=fmt(row["interval_E"]),
                outer_Omega=fmt(row["outer_Omega"]),
                outer_E=fmt(row["outer_E"]),
                D=fmt(row["D"]),
                K=fmt(row["K"]),
                C1=fmt(row["C1"]),
                C2=fmt(row["C2"]),
                tangent=row["tangent"],
                corrector=row["corrector"],
                iterations=row["iterations"],
                cuts=row["cuts"],
                cond=fmt(row["cond"]),
                pred_err=fmt(row["pred_err"]),
                nfev=row["nfev"],
                optimizer_success="yes" if row["optimizer_success"] else "no",
                message=str(row["message"]).replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
