"""Pseudo-arclength continuation test across the N=64 sonic-D wall."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imri_qpe.layer3_minidisk_1d import (
    TransonicSlimParams,
    pseudo_arclength_step,
    remap_profile_to_new_sonic_grid,
    solve_low_mdot_transonic_homotopy,
)
from imri_qpe.parameters import FiducialParams
from imri_qpe.scales import eddington_mdot


ROOT = Path(__file__).resolve().parents[1]
TABLE_OUTPUT = ROOT / "outputs" / "tables" / "transonic_n64_arclength.md"
RESIDUAL_TOL = 3.0e-4
R_OUT_RG = 3000.0
WARMUP_RATIOS = (1.0e-3, 2.5e-3, 5.0e-3, 1.0e-2, 2.0e-2, 3.0e-2)
N48_BRIDGE_RATIOS = (5.0e-2, 0.1, 0.2, 0.3)
N64_SEED_RATIOS = (0.3, 0.35)
SONIC_WEIGHTS = (0.3, 1.0, 3.0)
OUTER_WEIGHTS = (0.3, 0.7)


def fmt(value: float) -> str:
    if not np.isfinite(value):
        return "nan"
    return f"{value:.4g}"


def dominant_block(audit) -> str:
    values = {
        "interval_R": abs(audit.interval_radial_max),
        "interval_E": abs(audit.interval_energy_max),
        "outer_Omega": abs(audit.outer_omega),
        "outer_E": abs(audit.outer_energy),
        "D": abs(audit.sonic_D),
        "C1": abs(audit.sonic_C1),
        "C2": abs(audit.sonic_C2),
    }
    return max(values, key=values.get)


def accepted(status, max_residual: float) -> bool:
    return bool(
        np.isfinite(max_residual)
        and max_residual <= RESIDUAL_TOL
        and status.optimizer_acceptable
        and status.equations_converged
        and status.sonic_regular
        and status.active_bounds_clear
        and status.positive_state
        and status.outer_thin
    )


def solve_fixed(
    *,
    M2_g: float,
    mdot_edd: float,
    alpha: float,
    ratio: float,
    n_nodes: int,
    R_out_rg: float,
    seed_profile,
    sonic_weight_sequence: tuple[float, ...],
    outer_weight_sequence: tuple[float, ...],
    max_nfev: int,
    max_nfev_per_stage: int,
):
    params = TransonicSlimParams(
        M2_g=M2_g,
        Mdot_g_s=ratio * mdot_edd,
        alpha=alpha,
        n_nodes=n_nodes,
        R_out_rg=R_out_rg,
        max_nfev=max_nfev,
        residual_tol=RESIDUAL_TOL,
    )
    guess = remap_profile_to_new_sonic_grid(seed_profile, params) if seed_profile is not None else None
    result = solve_low_mdot_transonic_homotopy(
        params,
        initial_guess=guess,
        max_nfev_per_stage=max_nfev_per_stage,
        final_max_nfev=max_nfev,
        sonic_weight_sequence=sonic_weight_sequence,
        outer_weight_sequence=outer_weight_sequence,
    )
    return params, result


def row_from_fixed(label: str, ratio: float, n_nodes: int, result) -> dict[str, object]:
    final = result.final_result
    profile = final.profile
    audit = final.residual_audit
    status = final.status
    return {
        "label": label,
        "N": n_nodes,
        "ratio": ratio,
        "predicted_ratio": np.nan,
        "accepted": accepted(status, final.max_residual),
        "physical": status.physically_valid,
        "equations": status.equations_converged,
        "sonic": status.sonic_regular,
        "dominant": dominant_block(audit),
        "max_HR": float(np.max(profile.H_over_R)),
        "int_adv": profile.integrated_advective_fraction,
        "max_residual": final.max_residual,
        "interval_R": audit.interval_radial_max,
        "outer_Omega": audit.outer_omega,
        "D": audit.sonic_D,
        "C1": audit.sonic_C1,
        "C2": audit.sonic_C2,
        "arc": np.nan,
        "nfev": final.nfev,
        "message": final.message,
    }


def row_from_arc(result, step_multiplier: float) -> dict[str, object]:
    profile = result.profile
    audit = result.residual_audit
    status = result.status
    return {
        "label": f"arc_x{step_multiplier:g}",
        "N": result.params.n_nodes,
        "ratio": result.mdot_ratio,
        "predicted_ratio": result.predicted_mdot_ratio,
        "accepted": accepted(status, result.max_residual),
        "physical": status.physically_valid,
        "equations": status.equations_converged,
        "sonic": status.sonic_regular,
        "dominant": dominant_block(audit),
        "max_HR": float(np.max(profile.H_over_R)),
        "int_adv": profile.integrated_advective_fraction,
        "max_residual": result.max_residual,
        "interval_R": audit.interval_radial_max,
        "outer_Omega": audit.outer_omega,
        "D": audit.sonic_D,
        "C1": audit.sonic_C1,
        "C2": audit.sonic_C2,
        "arc": result.arclength_residual,
        "nfev": result.nfev,
        "message": result.message,
    }


def write_table(rows: list[dict[str, object]]) -> None:
    TABLE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# N=64 Pseudo-Arclength Continuation",
        "",
        "Generated by `scripts/run_transonic_n64_arclength.py`.",
        "",
        "The arclength segment starts from fixed-rate N64 seeds at `0.30` and `0.35`.",
        "",
        "| label | N | Mdot/Mdot_Edd | predicted | accepted | physical | equations | sonic | dominant | max H/R | int adv frac | max residual | interval R | outer Omega | D | C1 | C2 | arc residual | nfev | message |",
        "|---|---:|---:|---:|:---:|:---:|:---:|:---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append(
            "| {label} | {N} | {ratio} | {predicted_ratio} | {accepted} | {physical} | "
            "{equations} | {sonic} | {dominant} | {max_HR} | {int_adv} | {max_residual} | "
            "{interval_R} | {outer_Omega} | {D} | {C1} | {C2} | {arc} | {nfev} | {message} |".format(
                label=row["label"],
                N=row["N"],
                ratio=fmt(float(row["ratio"])),
                predicted_ratio=fmt(float(row["predicted_ratio"])),
                accepted="yes" if row["accepted"] else "no",
                physical="yes" if row["physical"] else "no",
                equations="yes" if row["equations"] else "no",
                sonic="yes" if row["sonic"] else "no",
                dominant=row["dominant"],
                max_HR=fmt(float(row["max_HR"])),
                int_adv=fmt(float(row["int_adv"])),
                max_residual=fmt(float(row["max_residual"])),
                interval_R=fmt(float(row["interval_R"])),
                outer_Omega=fmt(float(row["outer_Omega"])),
                D=fmt(float(row["D"])),
                C1=fmt(float(row["C1"])),
                C2=fmt(float(row["C2"])),
                arc=fmt(float(row["arc"])),
                nfev=row["nfev"],
                message=str(row["message"]).replace("|", "/"),
            )
        )
    TABLE_OUTPUT.write_text("\n".join(lines) + "\n")


def append_row(rows: list[dict[str, object]], row: dict[str, object]) -> None:
    rows.append(row)
    write_table(rows)
    print(
        f"{row['label']} N={row['N']} rate={row['ratio']:.4g} "
        f"accepted={row['accepted']} max={row['max_residual']:.4g} "
        f"outer={row['outer_Omega']:.4g} D={row['D']:.4g} dom={row['dominant']}",
        flush=True,
    )


def main() -> None:
    fiducial = FiducialParams()
    mdot_edd = eddington_mdot(fiducial.M2_g)
    rows: list[dict[str, object]] = []

    warmup_profile = None
    for ratio in WARMUP_RATIOS:
        _params, result = solve_fixed(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=24,
            R_out_rg=1000.0,
            seed_profile=warmup_profile,
            sonic_weight_sequence=(1.0,),
            outer_weight_sequence=(),
            max_nfev=1800,
            max_nfev_per_stage=800,
        )
        row = row_from_fixed("warmup", ratio, 24, result)
        append_row(rows, row)
        if row["accepted"] or (result.final_result.status.sonic_regular and result.final_result.max_residual < 8.0e-4):
            warmup_profile = result.final_result.profile

    bridge_profile = warmup_profile
    for ratio in N48_BRIDGE_RATIOS:
        _params, result = solve_fixed(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=48,
            R_out_rg=R_OUT_RG,
            seed_profile=bridge_profile,
            sonic_weight_sequence=SONIC_WEIGHTS,
            outer_weight_sequence=(),
            max_nfev=2000,
            max_nfev_per_stage=900,
        )
        row = row_from_fixed("bridge", ratio, 48, result)
        append_row(rows, row)
        if row["accepted"] or (result.final_result.status.sonic_regular and result.final_result.max_residual < 8.0e-4):
            bridge_profile = result.final_result.profile

    seed_profiles: list[object] = []
    seed_ratios: list[float] = []
    seed_profile = bridge_profile
    for ratio in N64_SEED_RATIOS:
        _params, result = solve_fixed(
            M2_g=fiducial.M2_g,
            mdot_edd=mdot_edd,
            alpha=fiducial.alpha_cool,
            ratio=ratio,
            n_nodes=64,
            R_out_rg=R_OUT_RG,
            seed_profile=seed_profile,
            sonic_weight_sequence=SONIC_WEIGHTS,
            outer_weight_sequence=OUTER_WEIGHTS,
            max_nfev=2200,
            max_nfev_per_stage=1000,
        )
        row = row_from_fixed("seed", ratio, 64, result)
        append_row(rows, row)
        if not row["accepted"]:
            print(f"stopping: seed rate {ratio:g} was not accepted", flush=True)
            return
        seed_profile = result.final_result.profile
        seed_profiles.append(seed_profile)
        seed_ratios.append(ratio)

    base_params = TransonicSlimParams(
        M2_g=fiducial.M2_g,
        Mdot_g_s=seed_ratios[-1] * mdot_edd,
        alpha=fiducial.alpha_cool,
        n_nodes=64,
        R_out_rg=R_OUT_RG,
        max_nfev=2200,
        residual_tol=RESIDUAL_TOL,
    )
    previous_ratio, current_ratio = seed_ratios
    previous_profile, current_profile = seed_profiles
    failures = 0
    step_multiplier = 1.0
    while current_ratio < 0.7 and failures < 3:
        result = pseudo_arclength_step(
            base_params,
            mdot_edd,
            previous_profile,
            previous_ratio,
            current_profile,
            current_ratio,
            step_multiplier=step_multiplier,
            mdot_ratio_bounds=(0.25, 0.9),
            max_nfev=1800,
            residual_tol=RESIDUAL_TOL,
            arclength_weight=10.0,
        )
        row = row_from_arc(result, step_multiplier)
        append_row(rows, row)
        if row["accepted"] and result.mdot_ratio > current_ratio * 1.001:
            previous_ratio, previous_profile = current_ratio, current_profile
            current_ratio, current_profile = result.mdot_ratio, result.profile
            failures = 0
            step_multiplier = 1.0
        else:
            failures += 1
            step_multiplier *= 0.5
            if step_multiplier < 0.125:
                break

    print(f"wrote {TABLE_OUTPUT}")


if __name__ == "__main__":
    main()
