#!/usr/bin/env python3
"""Freeze the conditioned discrete-gradient repair of the rejected entropy path."""
from __future__ import annotations
import argparse,csv,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
for p in (ROOT/"src",ROOT/"scripts"):
    if str(p) not in sys.path:sys.path.insert(0,str(p))
import run_causal_inner_local_nonlinear_atlas_trust_region_kernel_wp10c9d6c7c3b5c4f25fizzi1 as parent  # noqa:E402
WORK_PACKAGE="definitions_only_WP10c9d6c7c3b5c4f25fizzi2_conditioned_discrete_gradient_flux_manifest";CLASSIFICATION="conditioned_discrete_gradient_flux_manifest_frozen";AUTHORIZED_NEXT="WP10c9d6c7c3b5c4f25fizzi3_conditioned_discrete_gradient_flux_kernel";PASS_NEXT="definitions_only_WP10c9d6c7c3b5c4f25fizzj_bounded_nonlinear_split_microstep_manifest"
ARTIFACT="causal_inner_conditioned_discrete_gradient_flux_manifest_wp10c9d6c7c3b5c4f25fizzi2";CANONICAL_DIRECTORY=ROOT/"results/canonical"/ARTIFACT;REPORT_RELATIVE="docs/reports/current/CODEX_CAUSAL_INNER_CONDITIONED_DISCRETE_GRADIENT_FLUX_MANIFEST_WP10C9D6C7C3B5C4F25FIZZI2_2026-08-26.md";REPORT_PATH=ROOT/REPORT_RELATIVE;THIS_RUNNER="scripts/run_causal_inner_conditioned_discrete_gradient_flux_manifest_wp10c9d6c7c3b5c4f25fizzi2.py";THIS_TEST="tests/test_causal_inner_conditioned_discrete_gradient_flux_manifest_wp10c9d6c7c3b5c4f25fizzi2.py";PARENT_SHA256="a36a0aee55d7b44b4ea3f32391fd310924d5bf445176d2c1e10b5f07c85327eb";CANONICAL_MANIFEST=ROOT/"results/manifests/canonical_artifacts.csv";CANONICAL_SUMMARY=ROOT/"results/manifests/canonical_summary.json"
def _u():return parent._u()
def _validate_parent(clean=False):
 u=_u()
 if u._sha256(parent.CANONICAL_DIRECTORY/"SHA256SUMS.txt")!=PARENT_SHA256:raise RuntimeError("straight-path rejection checksum changed")
 h=u._validate_checksums(parent.CANONICAL_DIRECTORY);s=u._read_json(parent.CANONICAL_DIRECTORY/"summary.json");m=u._read_json(parent.CANONICAL_DIRECTORY/"kernel_metrics.json")
 if s["passed"] or m["passed"] or m["classification"]!=parent.FAIL_CLASSIFICATION or m["passing_endpoint_pair_count"]>=m["endpoint_pair_count"] or m["maximum_quadrature_refinement_relative_defect"]<=2e-9 or s["complete_cycle_execution_authorized"]:raise RuntimeError("straight-path rejection changed")
 if clean and u._git("status","--short","--untracked-files=no"):raise RuntimeError("discrete-gradient manifest needs clean tracked tree")
 return h
def _contract():return {"schema_version":1,"work_package":WORK_PACKAGE,"classification":CLASSIFICATION,"preserved":{"straight_entropy_path_rejected":True,"STF_polar_connection_supported":True,"endpoint_port_atlases_supported":True,"entropy_stable_frozen_discretization_certified":True},"repair":{"path_integration":False,"base_flux":"symmetric arithmetic mean of the two physical endpoint radial-current gradients","entropy_residual":"Delta X^R - Delta v dot f_base, evaluated with compensated alpha differences","correction":"minimum weighted-norm rank-one correction parallel to W^{-1} Delta v","weight":"diagonal endpoint physical-flux scale, frozen symmetrically","identity":"Delta v dot f_DG = Delta X^R by construction","symmetry":"f_DG(L,R)=f_DG(R,L)","consistency":"f_DG(U,U)=physical radial flux(U)","entropy_stable_extension":"subtract one-half lambda W^{-1} Delta v; its entropy production is non-positive"},"kernel":{"same_frozen_endpoint_pairs":376,"Tadmor_relative_gate":2e-12,"swap_symmetry_gate":2e-13,"consistency_gate":2e-13,"maximum_weighted_correction_relative_norm":.05,"penalty_positive_gate":0.0,"trajectory_steps":0},"decision":{"pass_classification":"conditioned_discrete_gradient_flux_kernel_certified","pass_authorized_next":PASS_NEXT,"failure_classification":"conditioned_discrete_gradient_flux_kernel_failed"},"claim_boundary":{"definitions_only":True,"straight_path_rescued":False,"bounded_nonlinear_microstep_authorized":False,"trajectory_authorized":False,"complete_cycle_execution_authorized":False},"authorized_next":AUTHORIZED_NEXT}
def _update(s):
 u=_u();rows=list(csv.DictReader(CANONICAL_MANIFEST.open(newline="",encoding="utf-8")));rows=[r for r in rows if r.get("case")!=ARTIFACT]
 for p in sorted(CANONICAL_DIRECTORY.iterdir()):
  if p.is_file():rows.append({"case":ARTIFACT,"path":str(p.relative_to(ROOT)),"bytes":str(p.stat().st_size),"sha256":u._sha256(p),"scientific_status":"SUPPORTED"})
 with CANONICAL_MANIFEST.open("w",newline="",encoding="utf-8") as h:w=csv.DictWriter(h,fieldnames=("case","path","bytes","sha256","scientific_status"),lineterminator="\n");w.writeheader();w.writerows(rows)
 c=u._read_json(CANONICAL_SUMMARY);c.setdefault("artifacts",{})[ARTIFACT]={"path":str(CANONICAL_DIRECTORY.relative_to(ROOT)),"classification":CLASSIFICATION,"passed":True};c.update({"case_count":len({r['case'] for r in rows}),"file_count":len(rows),"total_bytes":sum(int(r['bytes']) for r in rows),"all_payload_hashes_recorded":True,"latest_source_parent_commit":u._git("rev-parse","HEAD"),"latest_work_package":WORK_PACKAGE});u._write_json(CANONICAL_SUMMARY,c)
def _freeze():
 if CANONICAL_DIRECTORY.exists() or REPORT_PATH.exists():raise RuntimeError("discrete-gradient manifest exists")
 h=_validate_parent(True);u=_u();CANONICAL_DIRECTORY.mkdir(parents=True);u._write_json(CANONICAL_DIRECTORY/"discrete_gradient_contract.json",_contract());s={"schema_version":1,"work_package":WORK_PACKAGE,"classification":CLASSIFICATION,"passed":True,"definitions_only":True,"straight_entropy_path_rejection_preserved":True,"conditioned_discrete_gradient_flux_certified":False,"trajectory_authorized":False,"complete_cycle_execution_authorized":False,"authorized_next":AUTHORIZED_NEXT};u._write_json(CANONICAL_DIRECTORY/"summary.json",s);u._write_json(CANONICAL_DIRECTORY/"input_lock.json",{"parent_artifact":parent.ARTIFACT,"parent_checksum_manifest_sha256":PARENT_SHA256,"parent_hashes":h});REPORT_PATH.parent.mkdir(parents=True,exist_ok=True);REPORT_PATH.write_text("# Conditioned discrete-gradient flux manifest\n\nThe straight entropy path remains rejected. The replacement evaluates only physical endpoints and applies the unique weighted minimum-norm rank-one correction needed to satisfy the Tadmor identity. It is symmetric, consistent, and admits a sign-definite entropy penalty.\n\nThis package is definitions-only and authorizes no trajectory.\n",encoding="utf-8");src=(THIS_RUNNER,THIS_TEST,REPORT_RELATIVE);u._write_json(CANONICAL_DIRECTORY/"provenance.json",{"implementation_commit":u._git("rev-parse","HEAD"),"source_hashes":{p:u._sha256(ROOT/p) for p in src}});names=sorted(p.name for p in CANONICAL_DIRECTORY.iterdir());(CANONICAL_DIRECTORY/"SHA256SUMS.txt").write_text("".join(f"{u._sha256(CANONICAL_DIRECTORY/n)}  {n}\n" for n in names));_update(s);return s
def main():
 p=argparse.ArgumentParser();p.add_argument("--freeze",action="store_true");a=p.parse_args();
 if not a.freeze:p.error("choose --freeze")
 print(json.dumps(_freeze(),indent=2,sort_keys=True));return 0
if __name__=="__main__":raise SystemExit(main())
