"""Summarize the Mdot=5 energy-wind N/mesh validation runs."""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]

SOURCES: tuple[tuple[str, int, Path], ...] = (
    ("eps098", 768, ROOT / "outputs/tables/m5_energy_wind_mesh_validation_eps098_N768.json"),
    ("eps098", 896, ROOT / "outputs/tables/m5_energy_wind_anchor_freeze.json"),
    ("eps098", 1024, ROOT / "outputs/tables/m5_energy_wind_mesh_validation_eps098_N1024.json"),
    ("eta620", 768, ROOT / "outputs/tables/m5_energy_wind_mesh_validation_eta620_N768.json"),
    ("eta620", 896, ROOT / "outputs/tables/m5_energy_wind_anchor_freeze.json"),
    ("eta620", 1024, ROOT / "outputs/tables/m5_energy_wind_mesh_validation_eta620_N1024.json"),
    ("eta635", 768, ROOT / "outputs/tables/m5_energy_wind_mesh_validation_eta635_N768.json"),
    ("eta635", 896, ROOT / "outputs/tables/m5_energy_wind_anchor_freeze.json"),
    ("eta635", 1024, ROOT / "outputs/tables/m5_energy_wind_mesh_validation_eta635_N1024.json"),
)

ANCHOR_LABEL_FOR_STATE = {
    "eps098": "ewind_0p98",
    "eta620": "eta_6p20",
    "eta635": "eta_6p35",
}

STATE_LABEL = {
    "eps098": "epsilon_w=0.98",
    "eta620": "eta=6.20",
    "eta635": "eta=6.35",
}

JSON_OUTPUT = ROOT / "outputs/tables/m5_energy_wind_mesh_validation_summary.json"
MD_OUTPUT = ROOT / "outputs/tables/m5_energy_wind_mesh_validation_summary.md"


def _load_row(state: str, path: Path) -> dict[str, Any]:
    rows = json.loads(path.read_text())
    if not isinstance(rows, list):
        raise ValueError(f"{path} does not contain a row list")
    if path.name == "m5_energy_wind_anchor_freeze.json":
        wanted = ANCHOR_LABEL_FOR_STATE[state]
        for row in rows:
            if row.get("freeze_label") == wanted:
                return row
        raise ValueError(f"missing {wanted} in {path}")
    if len(rows) != 1:
        raise ValueError(f"expected one row in {path}, found {len(rows)}")
    return rows[0]


def _format(value: Any) -> str:
    if isinstance(value, str):
        return value
    try:
        number = float(value)
    except Exception:
        return str(value)
    if not math.isfinite(number):
        return "nan"
    if number == 0.0:
        return "0"
    if abs(number) < 1.0e-3 or abs(number) >= 1.0e4:
        return f"{number:.3e}"
    return f"{number:.6g}"


def main() -> None:
    rows: list[dict[str, Any]] = []
    for state, n_nodes, path in SOURCES:
        row = _load_row(state, path)
        rows.append(
            {
                "state": state,
                "state_label": STATE_LABEL[state],
                "N": int(n_nodes),
                "epsilon_w": float(row["wind_energy_limited_epsilon"]),
                "eta": float(row.get("energy_wind_eta", row.get("energy_wind_coordinate_target", math.nan))),
                "final_full": float(row["final_full"]),
                "physical_E": float(row.get("partition_physical_E", math.nan)),
                "buffer_E": float(row.get("partition_buffer_E", math.nan)),
                "peak_interval_E_rg": float(row.get("peak_interval_E_rg", math.nan)),
                "integrated_Qwind_Qvisc": float(row.get("integrated_Qwind_Qvisc", math.nan)),
                "Lrad_LEdd": float(row.get("Lrad_LEdd", math.nan)),
                "f_adv_global": float(row.get("f_adv_global", math.nan)),
                "f_adv_inner": float(row.get("f_adv_inner", math.nan)),
                "f_adv_pos": float(row.get("f_adv_pos", math.nan)),
                "max_H_R": float(row.get("max_H_R", math.nan)),
                "Rson_rg": float(row.get("Rson_rg", math.nan)),
                "Mdot_outer_over_inner": float(row.get("Mdot_outer_over_inner", math.nan)),
                "accepted": bool(row.get("accepted", False)),
                "dominant": str(row.get("dominant", "")),
                "source_path": str(path.relative_to(ROOT)),
            }
        )

    JSON_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUTPUT.write_text(json.dumps(rows, indent=2, sort_keys=True) + "\n")

    columns = [
        "state_label",
        "N",
        "final_full",
        "physical_E",
        "buffer_E",
        "integrated_Qwind_Qvisc",
        "Lrad_LEdd",
        "f_adv_global",
        "f_adv_inner",
        "f_adv_pos",
        "max_H_R",
        "Rson_rg",
        "accepted",
        "dominant",
    ]
    lines = [
        "# Mdot=5 Energy-Wind Mesh Validation Summary",
        "",
        "Generated by `scripts/summarize_mdot5_wind_mesh_validation.py`.",
        "",
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_format(row.get(column, "")) for column in columns) + " |")
    lines.append("")
    lines.append("## Sources")
    lines.append("")
    for row in rows:
        lines.append(f"- `{row['state_label']}`, N={row['N']}: `{row['source_path']}`")
    MD_OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {JSON_OUTPUT.relative_to(ROOT)}")
    print(f"wrote {MD_OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
